CREATE TABLE patch_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    published_date DATE NOT NULL,
    url VARCHAR(2048) NOT NULL
);

CREATE INDEX idx_patch_notes_published_date ON patch_notes (published_date DESC, id DESC);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    image VARCHAR(1024),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    url VARCHAR(2048)
);

CREATE INDEX idx_events_starts_at ON events (starts_at);
