CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    email VARCHAR(320),
    nickname VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_provider_identity UNIQUE (provider, provider_user_id)
);

-- character_id / weapon_id / main_echo_id / set_id는 프론트 config(characters.js 등)의 문자열 id입니다.
-- 카탈로그가 아직 DB에 없어서 FK 없이 값만 저장합니다.
CREATE TABLE character_builds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    character_id VARCHAR(50) NOT NULL,
    weapon_id VARCHAR(50),
    main_echo_id VARCHAR(50),
    -- false면 캐릭터 추천 세트 조합을 기본값으로 쓰고(프론트의 echoParts = null),
    -- true면 build_echo_sets 행이 사용자가 고른 조합입니다(행이 0개면 "세트 없음").
    echo_sets_customized BOOLEAN NOT NULL DEFAULT FALSE,
    base_char_atk NUMERIC(10, 2),
    base_weapon_atk NUMERIC(10, 2),
    base_hp NUMERIC(10, 2),
    base_def NUMERIC(10, 2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_character_builds_user_character UNIQUE (user_id, character_id)
);

CREATE INDEX idx_character_builds_character_id ON character_builds (character_id);

CREATE TABLE build_echo_sets (
    build_id BIGINT NOT NULL REFERENCES character_builds (id) ON DELETE CASCADE,
    set_id VARCHAR(50) NOT NULL,
    piece_count SMALLINT NOT NULL CHECK (piece_count > 0),
    PRIMARY KEY (build_id, set_id)
);

CREATE TABLE build_echoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    build_id BIGINT NOT NULL REFERENCES character_builds (id) ON DELETE CASCADE,
    slot SMALLINT NOT NULL CHECK (slot BETWEEN 0 AND 4),
    cost SMALLINT CHECK (cost IN (1, 3, 4)),
    CONSTRAINT uq_build_echoes_build_slot UNIQUE (build_id, slot)
);

-- 메인/서브 스탯을 한 테이블에 둡니다. value가 NULL이면 OCR이 수치를 못 읽은 줄입니다.
CREATE TABLE echo_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    echo_id BIGINT NOT NULL REFERENCES build_echoes (id) ON DELETE CASCADE,
    kind VARCHAR(4) NOT NULL CHECK (kind IN ('MAIN', 'SUB')),
    slot SMALLINT NOT NULL CHECK (slot >= 0),
    label VARCHAR(50) NOT NULL,
    value NUMERIC(8, 2),
    is_percent BOOLEAN NOT NULL DEFAULT FALSE,
    highlighted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_echo_stats_echo_kind_slot UNIQUE (echo_id, kind, slot)
);

CREATE INDEX idx_echo_stats_label ON echo_stats (label);
