-- 게임 기준 데이터(캐릭터·무기·에코 세트·메인 에코)입니다. 프론트 src/config/*.js에서 생성했습니다.
-- 이미지 파일은 프론트 public/에 두고 여기엔 경로만 저장합니다.
-- status: ACTIVE(공개) / HIDDEN(숨김) / UPCOMING(출시 예정), sort_order: 화면 노출 순서

CREATE TABLE characters (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    rarity SMALLINT NOT NULL CHECK (rarity BETWEEN 1 AND 5),
    element VARCHAR(10) NOT NULL,
    weapon_type VARCHAR(10),
    image_path VARCHAR(255),
    status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'HIDDEN', 'UPCOMING')),
    sort_order INT NOT NULL
);

CREATE TABLE character_base_stats (
    character_id VARCHAR(50) PRIMARY KEY REFERENCES characters (id) ON DELETE CASCADE,
    hp NUMERIC(10, 2) NOT NULL,
    atk NUMERIC(10, 2) NOT NULL,
    def NUMERIC(10, 2) NOT NULL,
    energy_regen NUMERIC(6, 2) NOT NULL,
    crit_rate NUMERIC(6, 2) NOT NULL,
    crit_dmg NUMERIC(6, 2) NOT NULL
);

CREATE TABLE character_innate_bonuses (
    character_id VARCHAR(50) NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
    sort_order SMALLINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    value NUMERIC(8, 2) NOT NULL,
    PRIMARY KEY (character_id, sort_order)
);

CREATE TABLE weapons (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(10) NOT NULL,
    icon_path VARCHAR(255),
    atk NUMERIC(8, 2) NOT NULL,
    sub_stat_category VARCHAR(50),
    sub_stat_value NUMERIC(8, 2),
    passive_name VARCHAR(100),
    description TEXT,
    status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'HIDDEN', 'UPCOMING')),
    sort_order INT NOT NULL
);

CREATE TABLE weapon_bonuses (
    weapon_id VARCHAR(50) NOT NULL REFERENCES weapons (id) ON DELETE CASCADE,
    sort_order SMALLINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    value NUMERIC(8, 2) NOT NULL,
    PRIMARY KEY (weapon_id, sort_order)
);

CREATE TABLE echo_sets (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    icon_path VARCHAR(255),
    status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'HIDDEN', 'UPCOMING')),
    sort_order INT NOT NULL
);

CREATE TABLE echo_set_effects (
    set_id VARCHAR(50) NOT NULL REFERENCES echo_sets (id) ON DELETE CASCADE,
    piece_count SMALLINT NOT NULL CHECK (piece_count > 0),
    description TEXT,
    PRIMARY KEY (set_id, piece_count)
);

CREATE TABLE echo_set_effect_bonuses (
    set_id VARCHAR(50) NOT NULL,
    piece_count SMALLINT NOT NULL,
    sort_order SMALLINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    value NUMERIC(8, 2) NOT NULL,
    PRIMARY KEY (set_id, piece_count, sort_order),
    FOREIGN KEY (set_id, piece_count) REFERENCES echo_set_effects (set_id, piece_count) ON DELETE CASCADE
);

CREATE TABLE main_echoes (
    id VARCHAR(80) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    icon_path VARCHAR(255),
    description TEXT,
    passive_description TEXT,
    status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'HIDDEN', 'UPCOMING')),
    sort_order INT NOT NULL
);

CREATE TABLE main_echo_bonuses (
    main_echo_id VARCHAR(80) NOT NULL REFERENCES main_echoes (id) ON DELETE CASCADE,
    sort_order SMALLINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    value NUMERIC(8, 2) NOT NULL,
    PRIMARY KEY (main_echo_id, sort_order)
);

-- 특정 캐릭터가 장착할 때만 추가로 붙는 보너스/설명입니다.
CREATE TABLE main_echo_character_bonuses (
    main_echo_id VARCHAR(80) NOT NULL REFERENCES main_echoes (id) ON DELETE CASCADE,
    character_id VARCHAR(50) NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
    sort_order SMALLINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    value NUMERIC(8, 2) NOT NULL,
    PRIMARY KEY (main_echo_id, character_id, sort_order)
);

CREATE TABLE main_echo_character_descriptions (
    main_echo_id VARCHAR(80) NOT NULL REFERENCES main_echoes (id) ON DELETE CASCADE,
    character_id VARCHAR(50) NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    PRIMARY KEY (main_echo_id, character_id)
);

CREATE TABLE echo_set_main_echoes (
    set_id VARCHAR(50) NOT NULL REFERENCES echo_sets (id) ON DELETE CASCADE,
    main_echo_id VARCHAR(80) NOT NULL REFERENCES main_echoes (id) ON DELETE CASCADE,
    sort_order SMALLINT NOT NULL,
    PRIMARY KEY (set_id, main_echo_id)
);

CREATE TABLE character_recommended_weapons (
    character_id VARCHAR(50) NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
    weapon_id VARCHAR(50) NOT NULL REFERENCES weapons (id) ON DELETE CASCADE,
    sort_order SMALLINT NOT NULL,
    PRIMARY KEY (character_id, weapon_id)
);

CREATE TABLE character_echo_combos (
    character_id VARCHAR(50) NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
    combo_no SMALLINT NOT NULL,
    PRIMARY KEY (character_id, combo_no)
);

CREATE TABLE character_echo_combo_parts (
    character_id VARCHAR(50) NOT NULL,
    combo_no SMALLINT NOT NULL,
    sort_order SMALLINT NOT NULL,
    set_id VARCHAR(50) NOT NULL REFERENCES echo_sets (id) ON DELETE CASCADE,
    piece_count SMALLINT NOT NULL CHECK (piece_count > 0),
    PRIMARY KEY (character_id, combo_no, sort_order),
    FOREIGN KEY (character_id, combo_no) REFERENCES character_echo_combos (character_id, combo_no) ON DELETE CASCADE
);

-- 점수 계산에 쓰는 캐릭터별 유효 서브옵션입니다. V3의 stat_labels 화이트리스트를 참조합니다.
CREATE TABLE character_valid_options (
    character_id VARCHAR(50) NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
    label VARCHAR(50) NOT NULL,
    kind VARCHAR(4) NOT NULL DEFAULT 'SUB' CHECK (kind = 'SUB'),
    sort_order SMALLINT NOT NULL,
    PRIMARY KEY (character_id, label),
    FOREIGN KEY (kind, label) REFERENCES stat_labels (kind, label)
);

INSERT INTO characters (id, name, rarity, element, weapon_type, image_path, sort_order) VALUES
    ('jiyan', '기염', 5, '기류', '대검', 'characters/jiyan.webp', 1),
    ('ciaccona', '샤콘', 5, '기류', '권총', 'characters/ciaccona.webp', 2),
    ('cartethyia', '카르티시아', 5, '기류', '직검', 'characters/cartethyia.webp', 3),
    ('rover_aero', '방랑자·기류', 5, '기류', '직검', 'characters/rover.webp', 4),
    ('iuno', '유노', 5, '기류', '권갑', 'characters/iuno.webp', 5),
    ('qiuyuan', '구원', 5, '기류', '직검', 'characters/qiuyuan.webp', 6),
    ('sigrika', '시그리카', 5, '기류', '권갑', 'characters/sigrika.webp', 7),
    ('encore', '앙코', 5, '용융', '증폭기', 'characters/encore.webp', 8),
    ('changli', '장리', 5, '용융', '직검', 'characters/changli.webp', 9),
    ('brant', '브렌트', 5, '용융', '직검', 'characters/brant.webp', 10),
    ('lupa', '루파', 5, '용융', '대검', 'characters/lupa.webp', 11),
    ('galbrena', '갈브레나', 5, '용융', '권총', 'characters/galbrena.webp', 12),
    ('mornye', '모니에', 5, '용융', '대검', 'characters/mornye.webp', 13),
    ('aemeath', '에이메스', 5, '용융', '직검', 'characters/aemeath.webp', 14),
    ('denia', '데니아', 5, '용융', '증폭기', 'characters/denia.webp', 15),
    ('zhezhi', '절지', 5, '응결', '증폭기', 'characters/zhezhi.webp', 16),
    ('carlotta', '카를로타', 5, '응결', '권총', 'characters/carlotta.webp', 17),
    ('lingyang', '능양', 5, '응결', '권갑', 'characters/lingyang.webp', 18),
    ('hiyuki', '히유키', 5, '응결', '직검', 'characters/hiyuki.webp', 19),
    ('lucilla', '루실라', 5, '응결', '증폭기', 'characters/lucilla.webp', 20),
    ('suisui', '수수', 5, '응결', '증폭기', 'characters/suisui.webp', 21),
    ('yinlin', '음림', 5, '전도', '증폭기', 'characters/yinlin.webp', 22),
    ('calcharo', '카카루', 5, '전도', '대검', 'characters/calcharo.webp', 23),
    ('xiangli_yao', '상리요', 5, '전도', '권갑', 'characters/xiangli_yao.webp', 24),
    ('augusta', '아우구스타', 5, '전도', '대검', 'characters/augusta.webp', 25),
    ('rebecca', '레베카', 5, '전도', '권총', 'characters/rebecca.webp', 26),
    ('rover_electro', '방랑자·전도', 5, '전도', '직검', 'characters/rover.webp', 27),
    ('rover_havoc', '방랑자·인멸', 5, '인멸', '직검', 'characters/rover.webp', 28),
    ('camellya', '카멜리아', 5, '인멸', '직검', 'characters/camellya.webp', 29),
    ('roccia', '로코코', 5, '인멸', '권갑', 'characters/roccia.webp', 30),
    ('cantarella', '칸타렐라', 5, '인멸', '증폭기', 'characters/cantarella.webp', 31),
    ('phrolova', '플로로', 5, '인멸', '증폭기', 'characters/phrolova.webp', 32),
    ('chisa', '치사', 5, '인멸', '대검', 'characters/chisa.webp', 33),
    ('Yangyang_Xuanling', '양양·현령', 5, '회절', NULL, 'characters/yangyang_xuanling.webp', 34),
    ('rover_spectro', '방랑자·회절', 5, '회절', '직검', 'characters/rover.webp', 35),
    ('verina', '벨리나', 5, '회절', '증폭기', 'characters/verina.webp', 36),
    ('jinhsi', '금희', 5, '회절', '대검', 'characters/jinhsi.webp', 37),
    ('shorekeeper', '파수인', 5, '회절', '증폭기', 'characters/shorekeeper.webp', 38),
    ('phoebe', '페비', 5, '회절', '증폭기', 'characters/phoebe.webp', 39),
    ('zeni', '젠니', 5, '회절', '권갑', 'characters/zeni.webp', 40),
    ('lynae', '린네', 5, '회절', '권총', 'characters/lynae.webp', 41),
    ('luuk_herssen', '루크·헤르센', 5, '회절', '권갑', 'characters/luuk_herssen.webp', 42),
    ('lucy', '루시', 5, '회절', '권총', 'characters/lucy.webp', 43);

INSERT INTO character_base_stats (character_id, hp, atk, def, energy_regen, crit_rate, crit_dmg) VALUES
    ('jiyan', 10487, 425, 1148, 100, 5, 150),
    ('ciaccona', 12237, 375, 1197, 100, 5, 150),
    ('cartethyia', 14800, 312, 611, 100, 5, 150),
    ('rover_aero', 10775, 437, 1136, 100, 5, 150),
    ('iuno', 10525, 450, 1124, 100, 5, 150),
    ('qiuyuan', 12237, 375, 1197, 100, 5, 150),
    ('sigrika', 10775, 437, 1136, 100, 5, 150),
    ('encore', 10512, 425, 1246, 100, 5, 150),
    ('changli', 10387, 462, 1099, 100, 5, 150),
    ('brant', 11675, 375, 1307, 100, 5, 150),
    ('lupa', 11912, 387, 1185, 100, 5, 150),
    ('galbrena', 10300, 462, 1112, 100, 5, 150),
    ('mornye', 15375, 287, 1356, 100, 5, 150),
    ('aemeath', 11025, 425, 1148, 100, 5, 150),
    ('denia', 11025, 425, 1148, 100, 5, 150),
    ('zhezhi', 12250, 375, 1197, 100, 5, 150),
    ('carlotta', 12450, 462, 1197, 100, 5, 150),
    ('lingyang', 12450, 462, 1197, 100, 5, 150),
    ('hiyuki', 10300, 462, 1112, 100, 5, 150),
    ('lucilla', 12237, 375, 1197, 100, 5, 150),
    ('suisui', 12237, 375, 1197, 100, 5, 150),
    ('yinlin', 11000, 400, 1283, 100, 5, 150),
    ('calcharo', 11000, 400, 1283, 100, 5, 150),
    ('xiangli_yao', 10625, 425, 1222, 100, 5, 150),
    ('augusta', 10300, 462, 1112, 100, 5, 150),
    ('rebecca', 11600, 400, 1173, 100, 5, 150),
    ('rover_electro', 10775, 437, 1136, 100, 5, 150),
    ('rover_havoc', 10825, 412, 1258, 100, 5, 150),
    ('camellya', 10325, 450, 1161, 100, 5, 150),
    ('roccia', 12250, 375, 1197, 100, 5, 150),
    ('cantarella', 11600, 400, 1099, 100, 5, 150),
    ('phrolova', 10775, 437, 1136, 100, 5, 150),
    ('chisa', 10775, 437, 1136, 100, 5, 150),
    ('rover_spectro', 11400, 375, 1368, 100, 5, 150),
    ('verina', 14237, 337, 1099, 100, 5, 150),
    ('jinhsi', 10825, 412, 1258, 100, 5, 150),
    ('shorekeeper', 16712, 287, 1099, 100, 5, 150),
    ('phoebe', 10825, 412, 1258, 100, 5, 150),
    ('zeni', 10775, 437, 1136, 100, 5, 150),
    ('lynae', 12237, 375, 1197, 100, 5, 150),
    ('luuk_herssen', 10300, 462, 1112, 100, 5, 150),
    ('lucy', 11025, 425, 1148, 100, 5, 150);

INSERT INTO character_innate_bonuses (character_id, sort_order, category, value) VALUES
    ('jiyan', 1, '크리티컬', 8),
    ('jiyan', 2, '공격력', 12),
    ('ciaccona', 1, '크리티컬 피해', 16),
    ('ciaccona', 2, '공격력', 12),
    ('cartethyia', 1, '크리티컬', 8),
    ('cartethyia', 2, 'HP', 12),
    ('rover_aero', 1, '치료 효과 보너스', 12),
    ('rover_aero', 2, '공격력', 12),
    ('iuno', 1, '크리티컬', 8),
    ('iuno', 2, '공격력', 12),
    ('qiuyuan', 1, '크리티컬', 8),
    ('qiuyuan', 2, '공격력', 12),
    ('sigrika', 1, '크리티컬', 8),
    ('sigrika', 2, '공격력', 12),
    ('encore', 1, '용융 피해 보너스', 12),
    ('encore', 2, '공격력', 12),
    ('changli', 1, '크리티컬', 8),
    ('changli', 2, '공격력', 12),
    ('brant', 1, '크리티컬', 8),
    ('brant', 2, '공격력', 12),
    ('lupa', 1, '크리티컬', 8),
    ('lupa', 2, '공격력', 12),
    ('galbrena', 1, '크리티컬 피해', 16),
    ('galbrena', 2, '공격력', 12),
    ('mornye', 1, '치료 효과 보너스', 12),
    ('mornye', 2, '방어력', 15.2),
    ('aemeath', 1, '크리티컬', 8),
    ('aemeath', 2, '공격력', 12),
    ('denia', 1, '크리티컬 피해', 16),
    ('denia', 2, '공격력', 12),
    ('zhezhi', 1, '크리티컬', 8),
    ('zhezhi', 2, '공격력', 12),
    ('carlotta', 1, '크리티컬', 8),
    ('carlotta', 2, '공격력', 12),
    ('lingyang', 1, '응결 피해 보너스', 12),
    ('lingyang', 2, '공격력', 12),
    ('hiyuki', 1, '크리티컬', 8),
    ('hiyuki', 2, '공격력', 12),
    ('lucilla', 1, '크리티컬', 8),
    ('lucilla', 2, '공격력', 12),
    ('suisui', 1, '크리티컬', 0),
    ('suisui', 2, '공격력', 0),
    ('yinlin', 1, '크리티컬', 8),
    ('yinlin', 2, '공격력', 12),
    ('calcharo', 1, '크리티컬 피해', 16),
    ('calcharo', 2, '공격력', 12),
    ('xiangli_yao', 1, '크리티컬 피해', 16),
    ('xiangli_yao', 2, '공격력', 12),
    ('augusta', 1, '크리티컬', 8),
    ('augusta', 2, '공격력', 12),
    ('rebecca', 1, '크리티컬', 8),
    ('rebecca', 2, '공격력', 12),
    ('rover_electro', 1, '크리티컬', 23),
    ('rover_electro', 2, '속성 피해 보너스', 10),
    ('rover_havoc', 1, '속성 피해 보너스', 22),
    ('camellya', 1, '크리티컬 피해', 16),
    ('camellya', 2, '공격력', 12),
    ('roccia', 1, '크리티컬 피해', 16),
    ('roccia', 2, '공격력', 12),
    ('cantarella', 1, '크리티컬', 8),
    ('cantarella', 2, '공격력', 12),
    ('phrolova', 1, '크리티컬', 8),
    ('phrolova', 2, '공격력', 12),
    ('chisa', 1, '크리티컬', 8),
    ('chisa', 2, '공격력', 12),
    ('rover_spectro', 1, '공명 효율', 10),
    ('rover_spectro', 2, '속성 피해 보너스', 12),
    ('verina', 1, '치료 효과 보너스', 12),
    ('verina', 2, '공격력', 12),
    ('jinhsi', 1, '크리티컬', 8),
    ('jinhsi', 2, '공격력', 12),
    ('shorekeeper', 1, '치료 효과 보너스', 12),
    ('shorekeeper', 2, 'HP', 12),
    ('phoebe', 1, '크리티컬 피해', 16),
    ('phoebe', 2, '공격력', 12),
    ('zeni', 1, '크리티컬', 8),
    ('zeni', 2, '공격력', 12),
    ('lynae', 1, '크리티컬', 8),
    ('lynae', 2, '공격력', 12),
    ('luuk_herssen', 1, '크리티컬', 8),
    ('luuk_herssen', 2, '공격력', 12),
    ('lucy', 1, '크리티컬', 8),
    ('lucy', 2, '공격력', 12);

INSERT INTO weapons (id, name, type, icon_path, atk, sub_stat_category, sub_stat_value, passive_name, description, sort_order) VALUES
    ('starfield-calibrator', '별하늘 연산 측정기', '대검', 'weapons/starfield-calibrator.webp', 412.5, '공명 효율', 77.04, '운명의 해답', '방어력이 16% 증가된다. 공명 스킬 발동 시, 자신의 협주 에너지를 8pt 회복하며, 20초마다 1회 발생할 수 있다. 치료 효과 발동 시, 근처 파티 내 모든 캐릭터의 크리티컬 피해를 20% 증가시키며, 4초간 지속된다. 같은 이름의 효과는 중첩이 불가하다', 1),
    ('kumokiri', '쿠모키리(曇斬)', '대검', 'weapons/kumokiri.webp', 500, '크리티컬', 36, '생명의 현', '공격력이 12% 증가된다. 변주 스킬 발동 혹은 「이상 효과」 추가 시, 자신의 공명 해방 피해 보너스가 8% 증가되고 최대 3스택까지 중첩이 가능하며 15초간 지속된다. 해당 효과가 스택 최대치까지 중첩될 경우, 파티 내 캐릭터가 「이상 효과」 추가 시 해당 캐릭터의 전체 속성 피해 보너스가 24% 증가되고, 15초간 지속된다. 같은 이름의 효과는 중첩이 불가하다', 2),
    ('thunderflare-dominion', '천둥벼락을 다스리는 권능', '대검', 'weapons/thunderflare-dominion.webp', 675, '크리티컬', 12.15, '불타오른 권력', '공격력이 12% 증가된다. 변주 스킬 혹은 공명 스킬 발동 시, 강공격 피해가 20% 증가되고 15초간 지속된다. 자신이 실드를 획득할 시 강공격 피해는 목표의 7.2% 방어력을 무시한다. 해당 효과는 0.5초마다 1회만 적용하며, 최대 5스택 중첩이 가능하고 7초간 지속된다', 3),
    ('wildfire-mark', '불길', '대검', 'weapons/wildfire-mark.webp', 587.5, '크리티컬 피해', 48.6, '눈부신 불빛', '공격력이 12% 증가된다. 변주 스킬 혹은 공명 해방 발동 시, 공명 해방 피해가 24% 증가되고 6초간 지속된다. 강공격 피해를 입힐 시, 해당 효과는 4초간 연장되며 최대 1회 연장할 수 있다. 효과 연장에 성공 시, 파티 내 캐릭터의 용융 피해 보너스가 24% 증가되고 30초간 지속된다. 같은 이름의 효과는 중첩이 불가하다', 4),
    ('lustrous-razor', '푸른물결의 빛', '대검', 'weapons/lustrous-razor.webp', 587.5, '공격력', 36.45, '밀려오는 파도', '공명 효율 12.8% 증가. 공명 스킬 발동 시, 공명 해방 피해 보너스가 7% 증가하고, 최대 3스택 중첩이 가능하며, 12초간 지속된다', 5),
    ('verdant-summit', '청룡의 천장', '대검', 'weapons/verdant-summit.webp', 587.5, '크리티컬 피해', 48.6, '용맹무쌍', '전체 속성 피해 보너스가 12% 증가한다. 변주 스킬 또는 공명 해방을 발동할 때마다, 자신의 강공격 피해 보너스가 24% 증가하고, 2스택 중첩이 가능하며, 14초간 지속된다', 6),
    ('ages-of-harvest', '태평성대', '대검', 'weapons/ages-of-harvest.webp', 587.5, '크리티컬', 24.3, '신의 가호', '전체 속성 피해 보너스가 12% 증가한다. 변주 스킬 발동 시, 자신이 「가호」를 획득하게 되고, 공명 스킬 피해 보너스를 24% 증가시키며, 12초간 지속된다. 공명 스킬 발동 시, 자신이 「축복」을 획득하게 되고, 공명 스킬 피해 보너스를 24% 증가시키며, 12초간 지속된다', 7),
    ('discord', '기묘한 울림', '대검', 'weapons/discord.webp', 337.5, '공명 효율', 51.84, '끝없는 메아리', '공명 스킬 발동 시, 협주 에너지 8pt를 회복하며, 20초마다 1회 발생할 수 있다', 8),
    ('autumntrace', '가을의 무늬', '대검', 'weapons/autumntrace.webp', 412.5, '크리티컬', 20.25, '검이 가리키는 곳', '일반 공격이나 강공격을 사용하여 피해를 입힐 경우, 공격력이 4% 증가하고, 최대 5스택 중첩이 가능하며, 7초간 지속되며, 1초마다 1회 발생할 수 있다', 9),
    ('azure-oath', '아득히 푸른 하늘', '직검', 'weapons/azure-oath.webp', 587.5, '크리티컬', 24.3, '홀로 솟은 깃', '전체 속성 피해 보너스가 12% 증가된다. 암흑 효과 추가 후, 강공격 피해가 36% 부스트되고, 강공격 피해는 목표의 12% 방어력을 무시하며, 8초간 지속된다', 10),
    ('frostburn', '서린 불꽃', '직검', 'weapons/frostburn.webp', 587.5, '크리티컬', 24.3, '다시는 나란 존재가 없기를', '공격력이 12% 증가된다. 자신이 서리 효과 추가 후 응결 피해가 28% 부스트되며 공명 해방 피해는 목표의 10% 방어력을 무시하고, 자신이 파티 내 등장 캐릭터일 시 일정 범위 내의 목표가 받는 서리 효과 피해가 20% 부스트되고, 6초간 지속되며 0.1초마다 1회 발생할 수 있다. 같은 이름의 효과는 더 높은 수치의 효과가 적용된다', 11),
    ('eternal-radiance', '영원한 샛별', '직검', 'weapons/eternal-radiance.webp', 587, '크리티컬', 24.3, '별을 좇아서', '전체 속성 피해 보너스가 12% 증가된다. 조화 파동·이탈 혹은 불꽃 효과 추가 시, 공명 해방 피해는 목표의 32% 방어력과 10%의 용융 저항을 무시하고, 8초간 지속된다.', 12),
    ('emerald-sentence', '푸른 의지', '직검', 'weapons/emerald-sentence.webp', 587.5, '크리티컬', 24.3, '굳건한 의지', '공격력이 12% 증가된다. 변주 스킬 혹은 일반 공격 발동 후 10초 내에, 에코 어빌리티 발동 시 「파죽(破竹)」 효과를 1스택 획득하고, 강공격 피해 보너스가 30% 증가된다. 같은 이름의 에코는 1회만 적용되고, 최대 2스택 중첩이 가능하며, 12초간 지속된다. 2스택까지 중첩 후 에코 어빌리티를 발동하면 지속 시간이 리셋되지 않는다. 해당 효과는 10초 내에 최대 1회 적용 가능하고, 다른 캐릭터로 전환하면 즉시 종료된다. 변주 스킬 발동 시, 파티 내 캐릭터의 에코 어빌리티 피해 보너스가 20% 증가되고 30초간 지속되며, 같은 이름의 효과는 중첩이 불가하다', 13),
    ('bloodpacts-pledge', '혈맹의 약속', '직검', 'weapons/bloodpacts-pledge.webp', 587.5, '공명 효율', 38.88, '화음 공진', '치료 효과 발동 시, 자신의 공명 스킬 피해가 10% 증가되고, 6초간 지속된다. 방랑자 · 기류가 공명 스킬 · 허무맹랑 발동 시, 근처 파티 내 등장 캐릭터의 기류 피해가 10% 부스트되고, 30초간 지속된다', 14),
    ('defiers-thorn', '숙명에 맞서는 관', '직검', 'weapons/defiers-thorn.webp', 412.5, 'HP', 72.23, '자유기사의 독무', 'HP가 12% 증가된다. 변주 스킬 혹은 일반 공격 발동 후 15초 내에, 자신이 입히는 피해가 목표의 8% 방어력을 무시하고, 목표가 1스택 이상의 풍식 효과를 보유 시 목표에게 입히는 피해가 20% 부스트된다', 15),
    ('unflickering-valor', '흔들리지 않는 용기', '직검', 'weapons/unflickering-valor.webp', 412.5, '공명 효율', 77.04, '웃음 바다', '크리티컬이 8% 증가된다. 공명 해방 발동 후, 일반 공격 피해 보너스가 24% 증가되고, 10초간 지속된다. 일반 공격 피해를 입힐 시, 일반 공격 피해 보너스가 24% 증가되고, 4초간 지속된다', 16),
    ('red-spring', '날카로운 봄', '직검', 'weapons/red-spring.webp', 587.5, '크리티컬', 24.3, '시작과 끝', '공격력이 12% 증가된다. 일반 공격 피해를 입힐 시, 자신의 일반 공격 피해 보너스가 10% 증가되고, 14초간 지속되며, 1초마다 1회 발생할 수 있고, 최대 3스택 중첩이 가능하다. 자신의 협주 에너지 소모 시, 자신의 일반 공격 피해 보너스가 40% 증가되며, 10초간 지속된다. 1초마다 1회 발생할 수 있다. 다른 캐릭터로 전환하면 효과가 즉시 종료된다', 17),
    ('blazing-brilliance', '솟아오르는 화염', '직검', 'weapons/blazing-brilliance.webp', 587.5, '크리티컬 피해', 48.6, '불사조의 깃털', '공격력이 12% 증가한다. 피해를 입힐 시 「빛나는 깃털」 1스택을 획득하며, 0.5초마다 1스택을 획득할 수 있다. 공명 스킬을 발동 시 추가로 5스택을 획득한다. 스택당 「빛나는 깃털」은 공명 스킬 피해 보너스를 4% 증가시키고, 최대 14스택까지 중첩이 가능하다. 「빛나는 깃털」이 14스택에 도달한 12초 후, 모든 스택이 리셋된다', 18),
    ('emerald-of-genesis', '천년의 회류', '직검', 'weapons/emerald-of-genesis.webp', 587.5, '크리티컬', 24.3, '무한의 소용돌이', '공명 효율 12.8% 증가. 공명 스킬 발동 시, 공격력이 6% 증가하고, 최대 2스택 중첩이 가능하며, 10초간 지속된다', 19),
    ('commando-of-conviction', '야귀의 신념', '직검', 'weapons/commando-of-conviction.webp', 412.5, '공격력', 30.38, '정면돌파', '변주 스킬 발동 시, 자신의 공격력이 15% 증가하며, 15초간 지속된다', 20),
    ('overture', '행진의 서곡', '직검', 'weapons/overture.webp', 337.5, '공명 효율', 51.84, '끝없는 메아리', '공명 스킬 발동 시, 협주 에너지 8pt를 회복하며, 20초마다 1회 발생할 수 있다', 21),
    ('skull-thrasher', '스컬 스래셔', '권총', 'weapons/skull-thrasher.webp', 500, '크리티컬 피해', 72, '홀로 깨어난 자', '공격력이 12% 증가된다. 변주 스킬 발동 시, 자신의 일반 공격 피해 보너스가 24% 증가되고, 14초간 지속된다. 「해킹 · 이탈」 추가 시, 자신의 일반 공격 피해 보너스가 12% 증가되고 14초간 지속되며, 파티 내 캐릭터의 공격력이 24% 증가되고 30초간 지속된다. 같은 이름의 효과는 중첩이 불가하다', 22),
    ('spectral-trigger', '스펙트럴 트리거', '권총', 'weapons/spectral-trigger.webp', 587.5, '크리티컬 피해', 48.6, '가라앉은 꿈', '공격력이 12% 증가된다. 공명 스킬 발동 시, 자신의 회절 피해 보너스가 20% 증가되고 최대 2스택 중첩이 가능하며, 14초간 지속된다. 적에게 「해킹 · 이탈」을 추가할 때마다, 강공격 피해가 30% 부스트되고 강공격 피해는 목표의 10% 방어력을 무시하며, 14초간 지속된다', 23),
    ('spectrum-blaster', '스펙트럼 블래스터', '권총', 'weapons/spectrum-blaster.webp', 587.5, '크리티컬', 24.3, '출석 면제 프로토콜', '공격력이 12% 증가된다. 변주 스킬 발동 혹은 일반 공격 피해로 목표 명중 시, 자신의 일반 공격 피해 보너스를 36% 증가시키고, 4초간 지속된다. 자신이 일반 공격 스킬을 발동하는 기간마다 목표에게 「조화 파동 · 이탈」 혹은 「조화 밀집 · 이탈」을 추가 시, 파티 내 캐릭터가 입히는 피해를 8% 증가시키고, 최대 3스택까지 중첩 가능하며, 30초간 지속된다. 같은 이름의 효과는 중첩이 불가하다', 24),
    ('lux-umbra', '얽혀진 빛과 그림자', '권총', 'weapons/lux-umbra.webp', 587.5, '크리티컬 피해', 48.6, '불의 귀환', '공격력이 12% 증가된다. 에코 어빌리티 피해를 입힐 시, 강공격 피해가 24% 부스트되고 6초간 지속된다. 강공격 피해를 입힐 시, 에코 어빌리티 피해가 24% 부스트되고, 6초간 지속된다. 단일 공격으로 최대 24%의 피해 부스트 효과를 얻는다. 두 가지 효과를 동시에 보유한 경우, 피해를 입힐 시 목표의 8% 방어력을 무시한다', 25),
    ('woodland-aria', '숲속의 아리아', '권총', 'weapons/woodland-aria.webp', 500, '크리티컬', 36, '한여름의 찬송가', '공격력이 12% 증가된다. 목표에게 「풍식 효과」를 추가한 후, 자신의 기류 피해 보너스가 24% 증가되고 10초간 지속된다. 공격으로 「풍식 효과」가 있는 목표 명중 시, 목표의 기류 저항을 10% 감소시키고, 20초간 지속된다. 같은 이름의 효과는 중첩이 불가하다', 26),
    ('the-last-dance', '죽음과 춤', '권총', 'weapons/the-last-dance.webp', 500, '크리티컬 피해', 72, '침묵 속의 추도사', '공격력이 12% 증가된다. 변주 스킬 혹은 공명 해방 발동 시, 자신의 공명 스킬 피해 보너스가 48% 증가되며, 5초간 지속된다', 27),
    ('phasic-homogenizer', '위상의 파동', '권총', 'weapons/phasic-homogenizer.webp', 587.5, '크리티컬 피해', 48.6, '통찰자', '공격력이 12% 증가된다. 파티 내 캐릭터가 「조화도 파괴 스킬」을 발동한 후, 자신의 전체 속성 피해 보너스가 20% 증가되고, 14초간 지속된다', 28),
    ('static-mist', '부동의 안개', '권총', 'weapons/static-mist.webp', 587.5, '크리티컬', 24.3, '지옥의 징벌', '공명 효율이 12.8% 증가한다. 반주 스킬 발동 후, 등장 캐릭터의 공격력이 10% 증가하고, 최대 1스택 중첩이 가능하며, 14초간 지속된다', 29),
    ('thunderbolt', '뇌전', '권총', 'weapons/thunderbolt.webp', 387.5, '공격력', 36.45, '거침없는 기세', '일반 공격이나 강공격을 사용하여 피해를 입힐 경우, 자신의 공명 스킬 피해 보너스가 7% 증가하고, 최대 3스택 중첩이 가능하며, 10초간 지속되고, 1초마다 1회 발생할 수 있다', 30),
    ('cadenza', '화려한 악곡', '권총', 'weapons/cadenza.webp', 337.5, '공명 효율', 51.84, '끝없는 메아리', '공명 스킬 발동 시, 협주 에너지 8pt를 회복하며, 20초마다 1회 발생할 수 있다', 31),
    ('solsworn-ciphers', '솔스원의 해석', '권갑', 'weapons/solsworn-ciphers.webp', 587.5, '크리티컬 피해', 48.6, '근일점', '공격력이 12% 증가된다. 변주 스킬 혹은 에코 어빌리티 발동 시, 에코 어빌리티 피해가 32% 부스트되고, 15초간 지속된다. 에코 어빌리티 피해를 입힐 시, 기류 피해는 목표의 10% 방어력을 무시하고, 6초간 지속된다', 32),
    ('daybreakers-spine', '한낮의 의지', '권갑', 'weapons/daybreakers-spine.webp', 587.5, '크리티컬 피해', 48.6, '봉합된 새벽과 황혼', '공격력이 12% 증가된다. 일반 공격 피해를 입힌 후, 회절 피해 보너스가 20% 증가되고, 4초간 지속된다. 매번 적에게 「조화 밀집 · 이탈」을 추가 후, 일반 공격 피해가 20% 부스트되고, 일반 공격 피해가 목표의 10% 방어력을 무시하며, 6초간 지속된다', 33),
    ('moongazers-sigil', '세상 만물의 진리', '권갑', 'weapons/moongazers-sigil.webp', 500, '크리티컬', 36, '만물을 연결하는 달', '공격력이 12% 증가된다. 변주 스킬 혹은 공명 해방 발동 시, 공명 해방 피해가 20% 증가되고, 15초간 지속된다. 자신이 실드를 획득할 시: 공명 해방 피해는 목표의 7.2% 방어력을 무시한다. 해당 효과는 0.5초마다 1회만 적용하며, 최대 5스택 중첩이 가능하고 7초간 지속된다. 변주 스킬 발동 시, 목표의 방어력을 무시하는 효과가 최대 스택으로 간주되고 3초간 지속된다', 34),
    ('blazing-justice', '불빛의 심판', '권갑', 'weapons/blazing-justice.webp', 587.5, '크리티컬 피해', 48.6, '어둠을 파괴하는 자', '공격력이 12% 증가된다. 일반 공격 발동 시 다음과 같은 효과를 획득한다. 자신이 입히는 피해가 목표의 방어력을 8% 무시하며, 동시에 자신이 직접 입히는 「광학 효과」 피해가 50% 부스트되고, 6초간 지속된다. 중복 획득 시, 지속 시간이 리셋된다', 35),
    ('tragicomedy', '희비극', '권갑', 'weapons/tragicomedy.webp', 587.5, '크리티컬', 24.3, '우인의 노래', '공격력이 12% 증가된다. 일반 공격 혹은 변주 스킬 발동 시, 자신의 강공격 피해 보너스가 48% 증가되며, 3초간 지속된다', 36),
    ('veritys-handle', '팔방의 천추', '권갑', 'weapons/veritys-handle.webp', 587.5, '크리티컬', 24.3, '근원의 추적', '전체 속성 피해 보너스가 12% 증가된다. 공명 해방 발동 시, 자신의 공명 해방 피해 보너스가 48% 증가되며, 8초간 지속된다. 공명 스킬 발동 시, 해당 효과가 5초 연장되며, 최대 3회 연장이 가능하다', 37),
    ('abyss-surges', '물결의 파동', '권갑', 'weapons/abyss-surges.webp', 587.5, '공격력', 36.45, '죽음의 심연', '공명 효율 12.8% 증가. 공명 스킬을 사용하여 피해를 입힐 경우, 일반 공격 피해 보너스가 10% 증가하며, 8초간 지속된다. 일반 공격을 사용하여 피해를 입힐 경우, 공명 스킬 피해 보너스가 10% 증가하며, 8초간 지속된다', 38),
    ('pulsation-bracer', '격동의 조력', '권갑', 'weapons/pulsation-bracer.webp', 587.5, '크리티컬', 24.3, '돌파자', '공격력이 12% 증가된다. 「조화 밀집 · 간섭」 상태에 있는 목표에게 피해를 입힌 후, 일반 공격 피해 보너스가 6% 증가되고, 3초간 지속되며, 최대 4스택까지 중첩이 가능하다. 해당 효과는 0.5초마다 1회 발생할 수 있으며, 중복 발생 시 지속 시간이 리셋된다', 39),
    ('stonard', '황금 권갑', '권갑', 'weapons/stonard.webp', 412.5, '크리티컬', 20.25, '불굴의 권갑', '공명 스킬 발동 시, 자신의 공명 해방 피해 보너스가 18% 증가하며, 15초간 지속된다', 40),
    ('celestial-spiral', '천상의 나선', '권갑', 'weapons/celestial-spiral.webp', 462.5, '공격력', 18.23, '피안의 눈동자', '공명 스킬 발동 시, 공명 에너지를 6pt 획득하고, 공격력이 10% 증가하며, 16초간 지속된다. 해당 효과는 20초마다 1회 발생할 수 있다', 41),
    ('firstlights-herald', '노을에 깃든 이슬', '증폭기', 'weapons/firstlights-herald.webp', 412.5, '공명 효율', 77.04, '비녀에 깃든 봄', 'HP가 12% 증가된다. 공명 해방 발동 시, 자신의 협주 에너지를 8pt 회복하고, 20초마다 1회 발생할 수 있다. 서리 효과를 추가할 때마다 「물들은 하얀 눈」을 획득하고, 6초간 지속된다. 치료 효과를 제공할 때마다 「생생한 잔물결」을 획득하고, 6초간 지속된다. 자신이 파티 내 등장 캐릭터일 시 서리 효과를 추가하고 치료 효과를 제공한 적이 있다면, 다음 반주 스킬 발동 시 6초간 지속되는 「물들은 하얀 눈」과 「생생한 잔물결」을 획득한다. 자신이 「물들은 하얀 눈」과 「생생한 잔물결」을 동시에 보유하고 있을 경우, 근처 파티 내 모든 캐릭터의 공격력이 20% 증가된다. 같은 이름의 효과는 중첩이 불가하다', 42),
    ('freeze-frame', '프리즈 프레임', '증폭기', 'weapons/freeze-frame.webp', 587.5, '크리티컬', 24.3, '페이드 아웃', '공격력이 12% 증가된다. 서리 효과 추가 후, 자신의 응결 피해 보너스가 30% 증가되고, 12초간 지속된다. 파티 내 캐릭터의 공격력이 24% 증가되고 30초간 지속되며, 같은 이름의 효과는 중첩이 불가하다', 43),
    ('forged-dwarf-star', '위조된 작은별', '증폭기', 'weapons/forged-dwarf-star.webp', 500, '크리티컬', 36, '적막', '공격력이 12% 증가된다. 불꽃 효과 혹은 조화 밀집 · 이탈 추가 후, 공명 해방 피해 보너스가 36% 증가되고 5초간 지속된다. 해당 효과 적용 기간 동안, 파티 내 캐릭터가 불꽃 효과 혹은 조화 밀집 · 이탈 추가 후, 해당 캐릭터의 공격력이 24% 증가되고 15초간 지속된다. 같은 이름의 효과는 중첩이 불가하다', 44),
    ('lethean-elegy', '잊혀진 피안의 슬픈 악장', '증폭기', 'weapons/lethean-elegy.webp', 587.5, '크리티컬', 24.3, '진혼곡', '공격력이 12% 증가된다. 에코 어빌리티 피해를 입힌 후 12초 내에, 공명 스킬 피해 보너스가 32% 증가되고, 에코 어빌리티 피해가 32% 부스트되며, 피해를 입힐 시 목표의 방어력을 8% 무시한다', 45),
    ('whispers-of-sirens', '바다의 속삭임', '증폭기', 'weapons/whispers-of-sirens.webp', 500, '크리티컬 피해', 72, '바닷속에서', '공격력이 12% 증가된다. 변주 스킬 혹은 일반 공격 발동 후 10초 내에, 에코 어빌리티 발동 시, 「부드러운 꿈」 1스택을 획득한다. 같은 이름의 에코는 1회만 발동이 가능하고, 최대 2스택 중첩이 가능하며, 10초간 지속된다. 2스택까지 중첩 후, 에코 어빌리티를 발동할 경우, 지속시간이 리셋되지 않는다. 해당 효과는 10초 내에 최대 1회 발생할 수 있으며, 다른 캐릭터로 전환하면 효과가 즉시 종료된다. 1스택: 일반 공격 피해 보너스가 40% 증가된다. 2스택: 목표의 인멸 속성 저항을 12% 무시한다', 46),
    ('luminous-hymn', '광휘의 찬송가', '증폭기', 'weapons/luminous-hymn.webp', 500, '크리티컬', 36, '단결자의 찬가', '공격력이 12% 증가된다. 「광학 효과」가 있는 목표에게 피해를 입힐 시, 자신의 일반 공격, 강공격 피해 보너스가 14% 증가되고, 최대 3스택 중첩이 가능하며, 6초간 지속된다. 반주 스킬 발동 시, 파티 내 등장 캐릭터 주변의 목표에게 주는 「광학 효과」 피해가 30% 부스트되고, 30초간 지속된다. 같은 이름의 효과는 중첩이 불가하다', 47),
    ('stellar-symphony', '뭇별의 교향곡', '증폭기', 'weapons/stellar-symphony.webp', 412.5, '공명 효율', 77.04, '뭇별의 법칙', 'HP가 12% 증가한다. 공명 해방 발동 시, 자신의 협주 에너지를 8pt 회복시키며, 20초마다 1회 발생할 수 있다. 공명 스킬로 치료 효과 발동 시, 근처 파티 내 모든 캐릭터의 공격력을 14% 증가시키며, 해당 효과는 30초간 지속된다. 같은 이름의 효과는 중첩이 불가하다', 48),
    ('rime-draped-sprouts', '옥수 비단', '증폭기', 'weapons/rime-draped-sprouts.webp', 500, '크리티컬 피해', 72, '그림 외의 경지', '공격력이 12% 증가된다. 공명 스킬 발동 시 획득 효과: 자신이 출전 상태일 시 일반 공격 피해 보너스가 12% 증가되며, 해당 효과가 최대 3스택 중첩이 가능하고, 6초간 지속된다. 반주 스킬 발동 시 이미 3스택의 효과가 누적된 경우, 모든 스택을 소모하여 자신이 출전 상태가 아닐 시의 일반 공격 피해 보너스를 52% 증가시키며, 27초간 지속된다', 49),
    ('stringmaster', '꼭두각시의 손', '증폭기', 'weapons/stringmaster.webp', 500, '크리티컬', 36, '뇌전의 증폭', '전체 속성 피해 보너스가 12% 증가한다. 공명 스킬 피해를 입힐 경우, 자신의 공격력이 12% 증가하고, 2스택 중첩이 가능하며, 5초간 지속된다. 자신이 미출전 상태일 경우, 공격력이 추가로 12% 증가한다', 50),
    ('cosmic-ripples', '파도의 기록', '증폭기', 'weapons/cosmic-ripples.webp', 500, '공격력', 54, '끝없는 물결', '공명 효율 12.8% 증가. 일반 공격을 사용하여 피해를 입힐 경우, 일반 공격 피해 보너스가 3.2% 증가하고, 최대 5스택 중첩이 가능하며, 8초간 지속되고, 0.5초마다 1회 발생할 수 있다', 51),
    ('oceans-gift', '바다의 선물', '증폭기', 'weapons/oceans-gift.webp', 462.5, '공격력', 18.23, '어획', '「광학 효과」가 있는 적에게 피해를 입힐 시 다음 효과를 얻을 수 있다. 자신의 회절 피해가 6% 증가되고, 1초마다 1스택을 획득할 수 있으며, 6초간 지속되고, 최대 4스택 중첩이 가능하다', 52),
    ('augment', '청음', '증폭기', 'weapons/augment.webp', 412.5, '크리티컬', 20.25, '강유병존', '공명 해방 발동 시, 자신의 공격력이 15% 증가하고, 15초간 지속된다', 53),
    ('call-of-the-abyss', '심해의 메아리', '증폭기', 'weapons/call-of-the-abyss.webp', 337.5, '공명 효율', 51.84, '은하수 조망', '공명 해방 발동 시, 자신의 치료 효과 보너스가 16% 증가하며, 15초간 지속된다', 54),
    ('variation', '판타지 변주', '증폭기', 'weapons/variation.webp', 337.5, '공명 효율', 51.84, '끝없는 메아리', '공명 스킬 발동 시, 협주 에너지 8pt를 회복하며, 20초마다 1회 발생할 수 있다', 55),
    ('rectifier-of-voyager', '수행자의 증폭기 · 탐색', '증폭기', 'weapons/rectifier-of-voyager.webp', 300, '공명 효율', 32.4, '기나긴 여정', '공명 스킬 발동 시, 공명 에너지 8pt를 회복하고, 20초마다 1회 발생할 수 있다', 56);

INSERT INTO weapon_bonuses (weapon_id, sort_order, category, value) VALUES
    ('starfield-calibrator', 1, '방어력', 16),
    ('kumokiri', 1, '공격력', 12),
    ('thunderflare-dominion', 1, '공격력', 12),
    ('wildfire-mark', 1, '공격력', 12),
    ('lustrous-razor', 1, '공명 효율', 12.8),
    ('verdant-summit', 1, '속성 피해 보너스', 12),
    ('ages-of-harvest', 1, '속성 피해 보너스', 12),
    ('azure-oath', 1, '속성 피해 보너스', 12),
    ('frostburn', 1, '공격력', 12),
    ('eternal-radiance', 1, '속성 피해 보너스', 12),
    ('emerald-sentence', 1, '공격력', 12),
    ('defiers-thorn', 1, 'HP', 12),
    ('unflickering-valor', 1, '크리티컬', 8),
    ('red-spring', 1, '공격력', 12),
    ('blazing-brilliance', 1, '공격력', 12),
    ('emerald-of-genesis', 1, '공명 효율', 12.8),
    ('skull-thrasher', 1, '공격력', 12),
    ('spectral-trigger', 1, '공격력', 12),
    ('spectrum-blaster', 1, '공격력', 12),
    ('lux-umbra', 1, '공격력', 12),
    ('woodland-aria', 1, '공격력', 12),
    ('the-last-dance', 1, '공격력', 12),
    ('phasic-homogenizer', 1, '공격력', 12),
    ('static-mist', 1, '공명 효율', 12.8),
    ('solsworn-ciphers', 1, '공격력', 12),
    ('daybreakers-spine', 1, '공격력', 12),
    ('moongazers-sigil', 1, '공격력', 12),
    ('blazing-justice', 1, '공격력', 12),
    ('tragicomedy', 1, '공격력', 12),
    ('veritys-handle', 1, '속성 피해 보너스', 12),
    ('abyss-surges', 1, '공명 효율', 12.8),
    ('pulsation-bracer', 1, '공격력', 12),
    ('firstlights-herald', 1, 'HP', 12),
    ('freeze-frame', 1, '공격력', 12),
    ('forged-dwarf-star', 1, '공격력', 12),
    ('lethean-elegy', 1, '공격력', 12),
    ('whispers-of-sirens', 1, '공격력', 12),
    ('luminous-hymn', 1, '공격력', 12),
    ('stellar-symphony', 1, 'HP', 12),
    ('rime-draped-sprouts', 1, '공격력', 12),
    ('stringmaster', 1, '속성 피해 보너스', 12),
    ('cosmic-ripples', 1, '공명 효율', 12.8);

INSERT INTO echo_sets (id, name, icon_path, sort_order) VALUES
    ('lamp-of-nether-road', '황천길을 밝히는 등불', 'echo-sets/lamp-of-nether-road.webp', 1),
    ('heart-of-evils-purge', '악을 씻어내는 마음', 'echo-sets/heart-of-evils-purge.webp', 2),
    ('song-of-feathered-trace', '내려앉은 깃털의 노래', 'echo-sets/song-of-feathered-trace.webp', 3),
    ('shadow-of-shattered-dreams', '꿈을 깨뜨리는 망령의 악몽', 'echo-sets/shadow-of-shattered-dreams.webp', 4),
    ('reel-of-spliced-memories', '마음을 엮은 꿈의 그림자', 'echo-sets/reel-of-spliced-memories.webp', 5),
    ('wishes-of-quiet-snowfall', '소리 없이 내려앉은 기도의 눈', 'echo-sets/wishes-of-quiet-snowfall.webp', 6),
    ('sound-of-true-name', '함의의 소리를 따라', 'echo-sets/sound-of-true-name.webp', 7),
    ('chromatic-foam', '오색찬란한 거품', 'echo-sets/chromatic-foam.webp', 8),
    ('trailblazing-star', '긴 여정을 떠나는 별', 'echo-sets/trailblazing-star.webp', 9),
    ('rite-of-gilded-revelation', '흐르는 금빛 속 진리의 답', 'echo-sets/rite-of-gilded-revelation.webp', 10),
    ('halo-of-starry-radiance', '빛을 쫓는 별의 고리', 'echo-sets/halo-of-starry-radiance.webp', 11),
    ('pact-of-neonlight-leap', '역광 속 눈부신 서약', 'echo-sets/pact-of-neonlight-leap.webp', 12),
    ('thread-of-severed-fate', '운명을 붕괴시키는 현', 'echo-sets/thread-of-severed-fate.webp', 13),
    ('flamewings-shadow', '불타는 깃털을 펼친 사냥꾼의 그림자', 'echo-sets/flamewings-shadow.webp', 14),
    ('law-of-harmony', '만물의 숨결에 비롯된 울림', 'echo-sets/law-of-harmony.webp', 15),
    ('crown-of-valor', '영광의 칼날로 만들어진 왕관', 'echo-sets/crown-of-valor.webp', 16),
    ('dream-of-the-lost', '뒤틀린 피안의 꿈', 'echo-sets/dream-of-the-lost.webp', 17),
    ('flaming-clawprint', '울부짖는 늑대의 불꽃', 'echo-sets/flaming-clawprint.webp', 18),
    ('windward-pilgrimage', '영광이 깃든 바람', 'echo-sets/windward-pilgrimage.webp', 19),
    ('gusts-of-welkin', '끝없는 하늘', 'echo-sets/gusts-of-welkin.webp', 20),
    ('tidebreaking-courage', '파도에 맞선 용기', 'echo-sets/tidebreaking-courage.webp', 21),
    ('empyrean-anthem', '하늘의 합주곡', 'echo-sets/empyrean-anthem.webp', 22),
    ('abyssal-veil', '어둠의 장막', 'echo-sets/abyssal-veil.webp', 23),
    ('eternal-radiance', '영원의 광채', 'echo-sets/eternal-radiance.webp', 24),
    ('frosty-resolve', '냉철한 결단', 'echo-sets/frosty-resolve.webp', 25),
    ('celestial-light', '빛나는 별', 'echo-sets/celestial-light.webp', 26),
    ('lingering-tunes', '끊임없는 잔향', 'echo-sets/lingering-tunes.webp', 27),
    ('moonlit-clouds', '떠오르는 구름', 'echo-sets/moonlit-clouds.webp', 28),
    ('rejuvenating-glow', '찬란한 광휘', 'echo-sets/rejuvenating-glow.webp', 29),
    ('havoc-eclipse', '빛을 삼키는 해', 'echo-sets/havoc-eclipse.webp', 30),
    ('sierra-gale', '스쳐가는 바람', 'echo-sets/sierra-gale.webp', 31),
    ('void-thunder', '울려퍼지는 뇌음', 'echo-sets/void-thunder.webp', 32),
    ('molten-rift', '솟구치는 용암', 'echo-sets/molten-rift.webp', 33),
    ('freezing-frost', '야밤의 서리', 'echo-sets/freezing-frost.webp', 34);

INSERT INTO echo_set_effects (set_id, piece_count, description) VALUES
    ('lamp-of-nether-road', 2, 'HP가 10% 증가된다'),
    ('lamp-of-nether-road', 5, '캐릭터가 실드 획득 시, 자신의 크리티컬이 5% 증가된다. 해당 효과는 최대 4스택 중첩이 가능하고 5초간 지속되며 0.5초마다 1회 발생할 수 있다. 최대 스택까지 중첩 시, 자신이 입히는 용융 피해가 15% 증가된다'),
    ('heart-of-evils-purge', 2, '기류 피해가 10% 증가된다'),
    ('heart-of-evils-purge', 5, '캐릭터가 적에게 「조화 밀집 · 이탈」 추가 시, 자신의 크리티컬 피해가 20% 증가되고 기류 피해가 30% 증가되며 15초간 지속된다'),
    ('song-of-feathered-trace', 2, '공명 효율이 10% 증가된다'),
    ('song-of-feathered-trace', 5, '캐릭터가 적에게 「암흑 효과」 추가 시, 「현령의 깃털」을 획득한다. 자신의 크리티컬이 20% 증가되고 강공격 피해 보너스가 35% 증가되며 15초간 지속된다. 캐릭터가 적에게 「서리 효과」 추가 시, 「중명조의 깃털」을 획득한다. 자신의 공명 효율 1% 당 파티 내 캐릭터의 공격력이 0.1% 증가되고 최대 25%까지 증가되며, 10초간 지속된다'),
    ('shadow-of-shattered-dreams', 1, '캐릭터가 적에게 「해킹 · 이탈」 추가 시, 자신의 일반 공격 피해 보너스와 강공격 피해 보너스가 35% 증가되며 15초간 지속된다'),
    ('reel-of-spliced-memories', 2, '공격력이 10% 증가된다'),
    ('reel-of-spliced-memories', 5, '캐릭터가 목표에게 「조화 파동 · 이탈」 혹은 「조화 밀집 · 이탈」 추가 시, 파티 내 캐릭터의 조화도 파괴 증폭이 20 증가되고, 30초간 지속된다. 같은 이름의 효과는 중첩이 불가하다'),
    ('wishes-of-quiet-snowfall', 2, '용융 피해가 10% 증가한다'),
    ('wishes-of-quiet-snowfall', 5, '캐릭터가 목표에게 「서리 효과」 추가 시, 응결 피해가 10% 증가되고, 15초간 지속된다. 자신이 「강설」 효과를 획득하고 15초간 지속되며, 해당 효과는 25초마다 1회 발생할 수 있다. 「강설」 효과 보유 시, 다음과 같은 효과를 획득한다. · 캐릭터가 공명 해방 피해를 입힐 시, 「강설」 효과를 제거하고 자신의 크리티컬을 25% 증가시키며, 6초간 지속된다. 해당 효과 지속 기간 동안 캐릭터가 공명 해방 피해를 입힐 시, 지속 시간은 4초 연장되고 0.5초마다 1회 발생할 수 있다. 매번 「강설」 효과 제거 후, 해당 효과는 최대 6회 발생할 수 있다. · 캐릭터가 반주 스킬 발동 시, 「강설」 효과를 제거하고 다음번 변주 스킬로 등장하는 캐릭터의 응결 피해를 25% 증가시키며 15초간 지속된다. 매번 「강설」 효과 제거 시, 위의 효과는 동시에 1개만 발생할 수 있다'),
    ('sound-of-true-name', 2, '용융 피해가 10% 증가한다'),
    ('sound-of-true-name', 5, '캐릭터가 에코 어빌리티 피해 입힐 시, 에코 어빌리티 피해의 크리티컬이 20% 증가되고 자신의 기류 피해가 15% 증가되며 5초간 지속된다'),
    ('chromatic-foam', 2, '용융 피해가 10% 증가한다'),
    ('chromatic-foam', 5, '캐릭터가 적에게 「불꽃 효과」 추가 시, 자신은 다음과 같은 효과를 획득한다. 용융 피해가 10% 증가되고, 15초간 지속된다. 지속 시간 내에 반주 스킬 발동 후, 다음 변주 스킬을 발동하여 등장하는 캐릭터의 용융 피해를 25% 증가시키고, 15초간 지속된다'),
    ('trailblazing-star', 2, '용융 피해가 10% 증가한다'),
    ('trailblazing-star', 5, '캐릭터가 적에게 「불꽃 효과」 혹은 「조화 파동·이탈」 추가 시, 자신의 크리티컬이 20% 증가되고 용융 피해가 20% 증가되며, 8초간 지속된다'),
    ('rite-of-gilded-revelation', 2, '회절 피해가 10% 증가된다'),
    ('rite-of-gilded-revelation', 5, '캐릭터가 일반 공격으로 피해를 입힐 시, 자신의 회절 피해가 10% 증가되고, 해당 효과는 3스택 중첩이 가능하며, 5초간 지속된다. 3스택까지 중첩 시, 공명 해방을 발동할 경우 일반 공격 피해 보너스가 40% 증가된다'),
    ('halo-of-starry-radiance', 2, '치료 효과가 10% 증가된다'),
    ('halo-of-starry-radiance', 5, '캐릭터가 파티원 치료 시, 자신의 부조화 수치 누적 효율 1% 당 파티 내 캐릭터의 공격력을 0.2% 증가시키고, 최대 25%까지 증가시키며, 4초간 지속된다. 같은 이름의 효과는 중첩이 불가하다'),
    ('pact-of-neonlight-leap', 2, '회절 피해가 10% 증가된다'),
    ('pact-of-neonlight-leap', 5, '캐릭터가 반주 스킬 발동 후, 다음번 변주 스킬로 등장하는 캐릭터의 공격력이 15% 증가된다. 조화도 파괴 증폭 1pt 당 공격력을 추가로 0.3% 증가시키고, 최대 15%까지 증가시키며, 15초간 지속된다. 다른 캐릭터로 전환하면 해당 효과는 즉시 종료된다'),
    ('thread-of-severed-fate', 3, '캐릭터가 적에게 「암흑 효과」 추가 시, 자신의 공격력이 20% 증가되고 공명 해방 피해 보너스가 30% 증가되며 5초간 지속된다'),
    ('flamewings-shadow', 3, '캐릭터가 에코 어빌리티 피해를 입힐 시, 강공격 피해의 크리티컬이 20% 증가되고 6초간 지속된다. 강공격 피해를 입힐 시, 에코 어빌리티 피해의 크리티컬이 20% 증가되고 6초간 지속된다. 두 가지 효과를 동시에 보유 시, 자신의 용융 피해가 16% 증가된다'),
    ('law-of-harmony', 3, '캐릭터가 에코 어빌리티 발동 시, 자신의 강공격 피해 보너스가 30% 증가되고 4초간 지속된다. 파티 내 캐릭터의 에코 어빌리티 피해 보너스가 4% 증가되고, 최대 4스택 중첩이 가능하며 30초간 지속된다. 같은 이름의 에코일 시 해당 효과는 1회만 발생할 수 있으며, 효과 종료 시 같은 이름의 에코의 기록은 리셋되고, 4스택까지 중첩 시 에코 어빌리티를 발동할 경우 지속시간은 리셋된다'),
    ('crown-of-valor', 3, '캐릭터가 실드 획득 시, 자신의 공격력이 6% 증가되고 크리티컬 피해가 4% 증가된다. 해당 효과는 최대 5스택까지 중첩이 가능하며, 4초간 지속되고 0.5초마다 1회 발생할 수 있다'),
    ('dream-of-the-lost', 3, '캐릭터의 공명 에너지가 0일 시, 자신의 크리티컬이 20% 증가되고, 에코 어빌리티 피해 보너스가 35% 증가된다'),
    ('flaming-clawprint', 2, '용융 피해가 10% 증가된다'),
    ('flaming-clawprint', 5, '공명 해방 발동 시, 파티 내 캐릭터의 용융 피해가 15% 증가되고, 자신의 공명 해방 피해가 20% 증가되며, 35초간 지속된다.'),
    ('windward-pilgrimage', 2, '기류 피해가 10% 증가된다'),
    ('windward-pilgrimage', 5, '캐릭터가 공격으로 「풍식 효과」가 있는 목표 명중 시, 자신의 크리티컬이 10% 증가되고, 기류 피해 보너스가 30% 증가되며, 10초간 지속된다.'),
    ('gusts-of-welkin', 2, '기류 피해가 10% 증가된다'),
    ('gusts-of-welkin', 5, '캐릭터가 적에게 「풍식 효과」를 추가할 경우, 파티 내 캐릭터의 기류 피해가 15% 증가되고, 자신의 기류 피해가 추가로 15% 증가되며, 20초간 지속된다'),
    ('tidebreaking-courage', 2, '공명 효율이 10% 증가된다'),
    ('tidebreaking-courage', 5, '현재 캐릭터의 협동 공격이 입히는 피해가 80% 증가된다. 협동 공격으로 적 명중 시 크리티컬이 발생할 경우, 파티 내 등장 캐릭터의 공격력이 20% 증가되고, 4초간 지속된다'),
    ('empyrean-anthem', 2, '공명 효율이 10% 증가된다'),
    ('empyrean-anthem', 5, '현재 캐릭터의 협동 공격이 입히는 피해가 80% 증가된다. 협동 공격으로 적 명중 시 크리티컬이 발생할 경우, 파티 내 등장 캐릭터의 공격력이 20% 증가되고, 4초간 지속된다'),
    ('abyssal-veil', 2, '인멸 피해가 10% 증가된다'),
    ('abyssal-veil', 5, '캐릭터의 반주 스킬이 발동되면서 퇴장 시, 추가로 주변 적에게 480%의 인멸 피해를 입히며 다음에 등장하는 캐릭터의 인멸 속성 피해 보너스를 15% 증가시키고 15초간 지속된다'),
    ('eternal-radiance', 2, '회절 피해가 10% 증가된다'),
    ('eternal-radiance', 5, '캐릭터가 적에게 「광학 효과」를 추가 시, 자신의 크리티컬이 20% 증가되고 15초간 지속된다. 「광학 효과」가 10스택인 적을 공격 시, 자신의 회절 피해 보너스가 15% 증가되고 15초간 지속된다'),
    ('frosty-resolve', 2, '공명 스킬 피해가 12% 증가된다'),
    ('frosty-resolve', 5, '공명 스킬 발동 시, 자신의 응결 피해가 22.5% 증가되고, 15초간 지속된다. 공명 해방 발동 시, 자신의 공명 스킬 피해가 18% 증가되고, 5초간 지속되며, 최대 2스택 중첩이 가능하다'),
    ('celestial-light', 2, '회절 피해가 10% 증가된다'),
    ('celestial-light', 5, '변주 스킬을 사용하여 등장 시, 회절 피해가 30% 증가되고, 15초 동안 지속된다'),
    ('lingering-tunes', 2, '공격력이 10% 증가된다'),
    ('lingering-tunes', 5, '출전 시, 자신의 공격력이 1.5초마다 5% 증가하며 해당 효과는 최대 4스택까지 중첩된다. 반주 스킬 피해가 60% 증가된다'),
    ('moonlit-clouds', 2, '공명 효율이 10% 증가된다'),
    ('moonlit-clouds', 5, '반주 스킬을 사용한 후, 다음에 등장하는 공명자의 공격력이 22.5% 증가하며, 15초 동안 지속된다'),
    ('rejuvenating-glow', 2, '치료 효과가 10% 증가된다'),
    ('rejuvenating-glow', 5, '파티원 치료 시, 파티 전체의 공격력이 15% 증가하며, 30초간 지속된다'),
    ('havoc-eclipse', 2, '인멸 피해가 10% 증가된다'),
    ('havoc-eclipse', 5, '일반 공격 또는 강공격 사용 시, 인멸 피해가 7.5% 증가하고 해당 효과는 4스택 중첩이 가능하며, 15초 동안 지속된다'),
    ('sierra-gale', 2, '기류 피해가 10% 증가된다'),
    ('sierra-gale', 5, '변주 스킬을 사용하여 등장 시, 기류 피해가 30% 증가하고, 15초 동안 지속된다'),
    ('void-thunder', 2, '전도 피해가 10% 증가된다'),
    ('void-thunder', 5, '강공격 또는 공명 스킬 사용 시, 전도 피해가 15% 증가된다, 해당 효과는 2스택 중첩이 가능하다, 각 스택당 15초 동안 지속된다'),
    ('molten-rift', 2, '용융 피해가 10% 증가된다'),
    ('molten-rift', 5, '공명 스킬 사용 시, 용융 피해가 30% 증가되며, 15초 동안 지속된다'),
    ('freezing-frost', 2, '응결 피해가 10% 증가된다'),
    ('freezing-frost', 5, '일반 공격이나 강공격을 사용하면, 응결 피해가 10% 증가 해당 효과는 3스택 중첩이 가능하며, 15초간 지속된다');

INSERT INTO echo_set_effect_bonuses (set_id, piece_count, sort_order, category, value) VALUES
    ('lamp-of-nether-road', 2, 1, 'HP', 10),
    ('heart-of-evils-purge', 2, 1, '속성 피해 보너스', 10),
    ('song-of-feathered-trace', 2, 1, '공명 효율', 10),
    ('reel-of-spliced-memories', 2, 1, '공격력', 10),
    ('wishes-of-quiet-snowfall', 2, 1, '속성 피해 보너스', 10),
    ('sound-of-true-name', 2, 1, '속성 피해 보너스', 10),
    ('chromatic-foam', 2, 1, '속성 피해 보너스', 10),
    ('trailblazing-star', 2, 1, '속성 피해 보너스', 10),
    ('rite-of-gilded-revelation', 2, 1, '속성 피해 보너스', 10),
    ('pact-of-neonlight-leap', 2, 1, '속성 피해 보너스', 10),
    ('flaming-clawprint', 2, 1, '속성 피해 보너스', 10),
    ('windward-pilgrimage', 2, 1, '속성 피해 보너스', 10),
    ('gusts-of-welkin', 2, 1, '속성 피해 보너스', 10),
    ('tidebreaking-courage', 2, 1, '공명 효율', 10),
    ('empyrean-anthem', 2, 1, '공명 효율', 10),
    ('abyssal-veil', 2, 1, '속성 피해 보너스', 10),
    ('eternal-radiance', 2, 1, '속성 피해 보너스', 10),
    ('frosty-resolve', 2, 1, '공명 스킬 피해', 12),
    ('celestial-light', 2, 1, '속성 피해 보너스', 10),
    ('lingering-tunes', 2, 1, '공격력', 10),
    ('moonlit-clouds', 2, 1, '공명 효율', 10),
    ('havoc-eclipse', 2, 1, '속성 피해 보너스', 10),
    ('sierra-gale', 2, 1, '속성 피해 보너스', 10),
    ('void-thunder', 2, 1, '속성 피해 보너스', 10),
    ('molten-rift', 2, 1, '속성 피해 보너스', 10),
    ('freezing-frost', 2, 1, '속성 피해 보너스', 10);

INSERT INTO main_echoes (id, name, icon_path, description, passive_description, sort_order) VALUES
    ('capitaneus', '카피타네우스', 'main-echoes/capitaneus.webp', '에코 어빌리티를 사용하여 카피타네우스를 소환하고, 목표를 향해 점프 후 내려찍고, 118.80%의 회절 피해를 입히며, 추가로 「매서운 판결」 4개를 생성하여 각각 59.40%의 회절 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 회절 피해 보너스가 12.00% 증가되고, 강공격 피해 보너스가 12.00% 증가된다.', 1),
    ('corrosaurus', '코로사우르스', 'main-echoes/corrosaurus.webp', '에코 어빌리티를 사용하여 코로사우루스를 소환하고 적에게 273.60%의 용융 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 용융 피해 보너스가 12.00% 증가되고, 에코 어빌리티 피해 보너스가 20.00% 증가된다.', 2),
    ('forbidden-bastion', '봉정계유', 'main-echoes/forbidden-bastion.webp', '에코 어빌리티를 사용하여 봉정계유를 소환한 후, 적에게 강타를 가하여 237.60%의 응결 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 치료 효과 보너스가 10.00% 증가된다.', 3),
    ('thundering-mephis', '뇌운의 비늘', 'main-echoes/thundering-mephis.webp', '에코 어빌리티를 사용하여 지옥불 기사로 변신한 후 참격을 발동한다. (최대 연속 사용 가능 횟수: 3회) 각각 242.40%, 282.80%, 282.80%의 용융 피해를 입힌다. 마지막 공격이 적에게 명중하면 자신의 용융 피해 보너스가 12.00% 증가하고, 일반 공격 피해 보너스가 12.00% 증가하며, 15초간 지속된다. 에코 어빌리티를 길게 누르면 변신 상태를 유지하면서 라이딩 상태에 진입하며, 종료 시 전방 목표에게 282.80%의 용융 피해를 1회 입힌다.', NULL, 4),
    ('inferno-rider', '지옥불 기사', 'main-echoes/inferno-rider.webp', '에코 어빌리티를 사용하여 지옥불 기사로 변신한 후 참격을 발동한다. (최대 연속 사용 가능 횟수: 3회) 각각 242.40%, 282.80%, 282.80%의 용융 피해를 입힌다. 마지막 공격이 적에게 명중하면 자신의 용융 피해 보너스가 12.00% 증가하고, 일반 공격 피해 보너스가 12.00% 증가하며, 15초간 지속된다. 에코 어빌리티를 길게 누르면 변신 상태를 유지하면서 라이딩 상태에 진입하며, 종료 시 전방 목표에게 282.80%의 용융 피해를 1회 입힌다.', NULL, 5),
    ('bell-borne-geochelone', '타종 거북이', 'main-echoes/bell-borne-geochelone.webp', '에코 어빌리티를 사용하여 타종 거북이의 가호를 발동하며 근처의 적에게 자신의 방어력 145.92%에 해당하는 응결 피해를 입히고 타종의 실드를 획득한다. (지속 시간: 15초) 타종의 실드는 파티 내 등장 캐릭터에게 50.00%의 피해 감소와 10.00%의 피해 증가를 제공하며, 3회 공격을 받은 후 사라진다.', NULL, 6),
    ('tempest-mephis', '천둥의 비늘', 'main-echoes/tempest-mephis.webp', '에코 어빌리티를 사용하여 천둥의 비늘로 변신한다. (최대 연속 사용 가능 횟수: 2회) 꼬리 흔들기로 소환한 번개 공격은 각 단마다 102.48%의 전도 피해를, 발톱 공격은 175.68%의 전도 피해를 입힌다. 발톱 공격 명중 후 캐릭터의 전도 피해 보너스는 12.00%, 강공격 피해 보너스는 12.00% 증가한다. (지속 시간: 15초)', NULL, 7),
    ('crownless', '크라운리스', 'main-echoes/crownless.webp', '에코 어빌리티를 사용하여 크라운리스로 변신한 후 최대 4회 연속 사용 가능하다. 처음 1~2회차에는 1단 134.08%의 인멸 피해를 입히며, 3회차는 2단 100.56%의 인멸 피해를 입히고, 4회차에는 3단 67.04%의 인멸 피해를 입힌다. 변신 후 자신의 인멸 피해 보너스가 12.00% 증가하며, 공명 스킬 피해 보너스가 12.00% 증가한다. (지속 시간: 15초)', NULL, 8),
    ('feilian-beringal', '폭주의 고릴라', 'main-echoes/feilian-beringal.webp', '에코 어빌리티를 사용하여 폭주의 고릴라로 변신한 후 발차기 공격을 진행하며 명중 시 추격 1회가 추가된다. 발차기 공격은 231.84%의 기류 피해를 입히며, 추격은 283.36%의 기류 피해를 입힌다. 추격으로 목표 명중 후, 자신의 기류 피해 보너스가 12.00% 증가하며, 강공격 피해 보너스가 12.00% 증가한다. (지속 시간: 15초)', NULL, 9),
    ('lampylumen-myriad', '반디의 군세', 'main-echoes/lampylumen-myriad.webp', '에코 어빌리티를 사용하여 반디의 군세로 변신한 후 공격을 하고 최대 3회 연속 사용할 수 있다. 앞으로 내리찍어 대범위의 얼음 충격을 일으킨다. 처음 1~2단 내리찍기는 200.16%과 200.16%의 응결 피해를 입히며, 마지막 1단은 266.88%의 응결 피해를 입혀 충격에 명중된 적들은 얼어붙는다. 매번 충격은 자신의 응결 피해 보너스가 4.00% 증가시키며, 공명 스킬 피해 보너스가 4.00% 증가시킨다. (지속 시간: 15초)', NULL, 10),
    ('mourning-aix', '애곡하는 아익스', 'main-echoes/mourning-aix.webp', '에코 어빌리티를 사용하여 애곡하는 아익스로 변신한 후 두번 연속의 발톱 공격을 발동하여 각각 157.44%, 236.16% 회절 피해를 입힌다. 에코 모습으로 변신한 후 캐릭터 회절 피해 보너스가 12.00% 증가하며, 공명 해방 피해 보너스가 12.00% 증가한다. (지속 시간: 15초)', NULL, 11),
    ('mech-abomination', '조립식 로봇', 'main-echoes/mech-abomination.webp', '에코 어빌리티를 사용하여 주변 적에게 48.64%의 전도 피해를 1회 입히고, 무기 폐기물을 모아 적을 공격한다. 폐기물이 목표에 명중 시 320.00%의 전도 피해를 입히고, 일정 시간 후 폭발하여 160.00%의 전도 피해를 입힌다. 에코 어빌리티 발동 후, 자신의 공격력이 12.00% 증가하며, 15초간 지속된다. 폐기물로 인한 피해는 캐릭터의 반주 스킬 피해로 간주된다.', NULL, 12),
    ('impermanence-heron', '음험한 백로', 'main-echoes/impermanence-heron.webp', '에코 어빌리티를 사용하여 음험한 백로로 변신한 후 날아올라 내리찍기 공격으로 310.56%의 인멸 피해를 입힌다. 에코 어빌리티를 길게 눌러 변신한 모습으로 날아오른 후 아래로 인멸 화염을 퍼붓는다. 각 단의 공격마다 55.73%의 인멸 피해를 입힌다. 변신 후 적에게 첫 명중 시, 자신의 공명 에너지를 10pt 회복하고, 이후의 15초 내에 자신이 반주 스킬 발동 시, 다음 교체 캐릭터의 피해를 12% 증가시킨다. (지속 시간: 15초)', NULL, 13),
    ('dreamless', '무망자', 'main-echoes/dreamless.webp', '에코 어빌리티를 사용하여 무망자로 변신한 후 전방의 목표를 6회 연속 공격한다. 처음 1~5회까지 매회 54.08%의 인멸 피해를 입히고 마지막 1회는 270.40%의 인멸 피해를 입힌다. 방랑자 · 인멸은 공명 해방 · 임연사적을 발동한 후 5초 이내에, 해당 에코 어빌리티 발동으로 인한 피해가 50.00% 증가한다.', NULL, 14),
    ('jue', '용의 별자리', 'main-echoes/jue.webp', '에코 어빌리티를 사용하여 「용의 별자리」를 소환하면 하늘로 승천하며, 적에게 48.64% 회절 피해를 입힌다. 동시에 주변의 적에게 최대 5단까지 벼락을 방출하며, 매 단마다 19.46% 회절 피해를 입힌다. 이어 「용의 별자리」는 아래로 내려와 주변 적에게 회전 공격하여 두 번 연속 48.64% 회절 피해를 입힌다. 해당 에코 어빌리티를 장착한 캐릭터는 「세월의 축복」을 획득하며, 15초 동안 지속된다. 「세월의 축복」 지속 기간: · 자신의 공명 스킬 피해 보너스가 16.00% 증가한다. · 자신의 공명 스킬로 적을 명중할 시, 해당 적은 초당 16.00% 회절 피해를 받는다. 이번 피해는 캐릭터의 공명 스킬 피해로 적용되며 15초 간 지속된다.', NULL, 15),
    ('fallacy-of-no-return', '돌아갈 곳이 없는 오류', 'main-echoes/fallacy-of-no-return.webp', '에코 어빌리티를 사용하여 돌아갈 곳이 없는 오류의 일부 권능을 소환한다. 주위의 적에게 자신의 HP 최대치의 15.86%에 해당하는 회절 피해를 1회 입히고 자신의 공명 효율이 10% 증가하며, 파티 내 모든 캐릭터의 공격력을 10% 증가시킨다. 해당 효과는 20초간 지속된다. 에코 어빌리티를 길게 누르면, 쇼크 공격 종료 후 스태미나를 소모하여 지속적인 공격을 진행한다. 매번 공격이 HP 최대치의 1.58%에 해당하는 회절 피해를 입힌다. 길게 누르기 종료 후 최후의 일격이 발생하여 HP 최대치의 19.82%에 해당하는 회절 피해를 입힌다.', NULL, 16),
    ('lorelei', '로렐라이', 'main-echoes/lorelei.webp', '에코 어빌리티를 사용하여 로렐라이로 변신한 후, 주변 적에게 405.00%의 인멸 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 인멸 피해 보너스가 12.00% 증가하고, 일반 공격 피해 보너스가 12.00% 증가한다.', 17),
    ('sentry-construct', '이성(異性) 무장', 'main-echoes/sentry-construct.webp', '에코 어빌리티를 사용하여 이성(異性) 무장으로 변신한 후, 전방의 목표를 공격하여 405.00%의 응결 피해를 입힌다. 해당 에코를 장착한 캐릭터가 공명 해방 발동 시, 「강습 출력」을 지속적으로 증가시킬 수 있다. 「강습 출력」이 가득 찰 시, 에코 어빌리티 쿨타임이 리셋되고, 에코 어빌리티를 사용하여 이성(異性) 무장으로 변신하면 도약한 후 목표를 향해 급강하하여 405.00%의 응결 피해를 입히고 목표를 동결시킨다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 응결 피해 보너스가 12.00% 증가하고, 공명 스킬 피해 보너스가 12.00% 증가한다.', 18),
    ('dragon-of-dirge', '탄식의 고룡', 'main-echoes/dragon-of-dirge.webp', '에코 어빌리티를 사용하여 탄식의 고룡으로 변신한 후, 5초간 지속되는 「비통의 영역」을 소환하고 주기적으로 「비통의 영역」 내에 있는 적에게 36.81%의 용융 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 용융 피해 보너스가 12.00% 증가하고, 일반 공격 피해 보너스가 12.00% 증가한다.', 19),
    ('hecate', '헤카테', 'main-echoes/hecate.webp', '에코 어빌리티를 사용하여 주변에 3개의 지속적으로 회전하며 춤추는 「명월의 시녀」를 소환한다. 「명월의 시녀」의 회전칼은 적에게 45.59%의 인멸 피해를 입힌다. 회전칼이 패링을 성공할 시 「명월의 시녀」의 존재 시간이 리셋된다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시 자신의 협동 공격이 입히는 피해가 40.00% 증가한다.', 20),
    ('nightmare-feilian-beringal', '악몽 · 폭주의 고릴라', 'main-echoes/nightmare-feilian-beringal.webp', '에코 어빌리티를 사용하여 악몽 · 폭주의 고릴라를 소환해 적을 공격하고 164.16%의 기류 피해를 입힌다. 남겨진 「바람의 기둥」은 지속적으로 주변의 적을 공격하고, 적에게 최대 5단, 매 단마다 21.89%의 기류 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시 자신의 기류 피해 보너스가 12.00% 증가하고 강공격 피해 보너스가 12.00% 증가한다.', 21),
    ('nightmare-impermanence-heron', '악몽 · 음험한 백로', 'main-echoes/nightmare-impermanence-heron.webp', '에코 어빌리티를 사용하여 악몽 · 음험한 백로로 변신한 후, 주변 적에게 최대 10단, 매 단마다 40.50%의 인멸 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 인멸 피해 보너스가 12.00% 증가하고, 강공격 피해 보너스가 12.00% 증가한다.', 22),
    ('nightmare-thundering-mephis', '악몽 · 뇌운의 비늘', 'main-echoes/nightmare-thundering-mephis.webp', '에코 어빌리티를 사용하여 악몽 · 뇌운의 비늘로 변신한 후, 전방의 적에게 405.00%의 전도 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 전도 피해 보너스가 12.00% 증가하고, 공명 해방 피해 보너스가 12.00% 증가한다.', 23),
    ('nightmare-tempest-mephis', '악몽 · 천둥의 비늘', 'main-echoes/nightmare-tempest-mephis.webp', '에코 어빌리티를 사용하여 악몽 · 천둥의 비늘로 변신한 후, 주변 적에게 405.00%의 전도 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 전도 피해 보너스가 12.00% 증가하고, 공명 스킬 피해 보너스가 12.00% 증가한다.', 24),
    ('nightmare-crownless', '악몽 · 크라운리스', 'main-echoes/nightmare-crownless.webp', '에코 어빌리티를 사용하여 악몽 · 크라운리스로 변신한 후, 전방의 적에게 264.60%의 인멸 피해를 입힌다. 초기 3회 발동 가능 횟수를 보유하며, 12초마다 발동 가능 횟수가 1회씩 증가한다. 발동 가능 횟수의 누적 최대치는 3회이다. 악몽 · 크라운리스가 목표 명중 후, 해당 에코 어빌리티가 입히는 피해가 20.00% 증가하고, 2초간 지속되며, 중첩이 불가하다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 인멸 피해 보너스가 12.00% 증가하고, 일반 공격 피해 보너스가 12.00% 증가한다.', 25),
    ('nightmare-inferno-rider', '악몽 · 지옥불 기사', 'main-echoes/nightmare-inferno-rider.webp', '에코 어빌리티를 사용하여 악몽 · 지옥불 기사로 변신한 후, 도약하여 전방의 적에게 405.00%의 용융 피해를 입힌다. 에코 어빌리티를 길게 누르면 변신 상태를 유지하면서 라이딩 상태에 진입하며, 종료 시 전방 목표에게 283.50%의 용융 피해를 1회 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 용융 피해 보너스가 12.00% 증가하고, 공명 스킬 피해 보너스가 12.00% 증가한다.', 26),
    ('nightmare-mourning-aix', '악몽 · 애곡하는 아익스', 'main-echoes/nightmare-mourning-aix.webp', '에코 어빌리티를 사용하여 악몽 · 애곡하는 아익스를 소환해 주변 적에게 273.60%의 회절 피해를 입힌다. 적이 「광학 효과」 영향을 받고 있는 상태일 시 애곡하는 아익스가 입히는 피해가 100.00% 증가한다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 회절 피해 보너스가 12.00% 증가한다.', 27),
    ('nightmare-lampylumen-myriad', '악몽 · 반디의 군세', 'main-echoes/nightmare-lampylumen-myriad.webp', '에코 어빌리티를 사용하여 악몽 · 반디의 군세를 소환하고, 주변 적에게 273.60%의 응결 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 응결 피해 보너스가 12.00% 증가되고, 협동 공격이 입히는 피해가 30.00% 증가된다.', 28),
    ('nightmare-kelpie', '악몽 · 켈피', 'main-echoes/nightmare-kelpie.webp', '에코 어빌리티를 사용하여 악몽 · 켈피로 변신한 후, 주변 적에게 405.00%의 응결 피해를 입힌다. 반주 스킬을 발동하고 퇴장 시 악몽 · 켈피를 소환하여 적에게 405.00%의 기류 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 응결 피해 보너스가 12.00% 증가되고, 기류 피해 보너스가 12.00% 증가된다.', 29),
    ('nightmare-hecate', '악몽 · 헤카테', 'main-echoes/nightmare-hecate.webp', '에코 어빌리티를 사용하여 악몽 · 헤카테로 변신한 후, 위로 뛰어오른 뒤 내리쳐 각각 152.39%의 인멸 피해를 3단 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 인멸 피해 보너스가 12.00% 증가되고, 에코 어빌리티 피해 보너스가 20.00% 증가된다.', 30),
    ('reminiscence-fleurdelys', '공명의 메아리 · 플뢰르 드 리스', 'main-echoes/reminiscence-fleurdelys.webp', '에코 어빌리티를 사용하여 「윈드 클리버」를 소환한 후, 목표를 공격하여 8단 27.36% 및 1단 136.80%의 기류 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 기류 피해 보너스가 10.00% 증가된다. 장착 캐릭터가 방랑자 · 기류 혹은 카르티시아일 경우, 자신의 기류 피해 보너스가 추가로 10.00% 증가된다.', 31),
    ('reminiscence-fenrico', '공명의 메아리 · 펜리코', 'main-echoes/reminiscence-fenrico.webp', '에코 어빌리티를 사용하여 「계율의 발톱」을 소환한 후, 주변 목표에게 273.60%의 기류 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 기류 피해 보너스가 12.00% 증가되고, 강공격 피해 보너스가 12.00% 증가된다.', 32),
    ('reminiscence-threnodian-leviathan', '공명의 메아리 · 명식 · 레비아탄', 'main-echoes/reminiscence-threnodian-leviathan.webp', '에코 어빌리티를 사용하여 「시야 붕괴」를 소환하고 주변 적에게 2단 131.04%의 인멸 피해를 입히고, 핵심 붕괴를 획득하며 15초간 지속된다. 핵심 붕괴가 존재하는 기간 동안, 파티 내 등장 캐릭터가 피해를 입힐 시 추가로 1단 24.57% 인멸 피해를 추가하고 해당 효과는 8회 발생할 수 있으며 0.5초마다 최대 1회 발생한다. 적이 「암흑 효과」의 영향을 받은 상태인 경우, 해당 효과로 입히는 피해가 100% 증가된다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 인멸 피해 보너스가 12.00% 증가되고, 공명 해방 피해 보너스가 12.00% 증가된다.', 33),
    ('reminiscence-threnodian-voidborne-construct', '공명의 메아리 · 명식 · 허무의 신', 'main-echoes/reminiscence-threnodian-voidborne-construct.webp', '에코 어빌리티를 사용하여 알레프-원의 창조물을 소환한 후, 적에게 5단 21.88%과 1단 164.16%의 응결 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 응결 피해 보너스가 12.00% 증가하고, 공명 해방 피해 보너스가 12.00% 증가한다.', 34),
    ('reminiscence-denia', '공명의 메아리 · 데니아', 'main-echoes/reminiscence-denia.webp', '에코 어빌리티 사용하여 「속임수의 대가」를 소환한 후, 적에게 273.60%의 용융 피해를 입힌다. 이후 15초 내에 자신의 반주 스킬을 발동 시, 다음번 변주 스킬로 등장하는 캐릭터의 용융 피해 보너스를 12.00% 증가시키고, 15초간 지속된다.', NULL, 35),
    ('reminiscence-nightmare-adam-smasher', '공명의 메아리 · 악몽 아담 · 스매셔', 'main-echoes/reminiscence-nightmare-adam-smasher.webp', '에코 어빌리티 사용 시, 범위 내의 목표에게 총 16단 10.26%의 물리 피해를 입힌다. 루시에게 장착 시, 에코 어빌리티가 다음과 같이 대체된다. · 에코 어빌리티를 짧게 누르면 주변 목표에게 273.60%의 회절 피해를 입힌다. · 에코 어빌리티를 길게 누르면 주변 목표에게 273.60%의 회절 피해를 입히고, 특수 이동 상태에 진입하며 지속 기간 동안 루시의 이동 속도를 증가시키고 주변 목표의 시간 흐름을 늦춘다. 레베카에게 장착 시, 에코 어빌리티가 다음과 같이 대체된다. · 에코 어빌리티 사용 시, 미사일을 발사하여 목표에게 16단 17.10%의 전도 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티 장착 시, 장착 캐릭터가 루시 혹은 레베카일 경우 자신의 크리티컬이 15% 증가되고, 에코 어빌리티 또한 장착된 캐릭터에 따라 해당하는 특수 효과로 대체된다.', 36),
    ('lioness-of-glory', '영광의 사자', 'main-echoes/lioness-of-glory.webp', '에코 어빌리티를 사용하여 「영광의 폴암」을 소환한 후, 주변 적에게 82.08%의 용융 피해를 입히고, 일정 시간 후 다시 191.52%의 용융 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 용융 피해 보너스가 12.00% 증가되고, 공명 해방 피해 보너스가 12.00% 증가된다.', 37),
    ('the-false-sovereign', '거짓의 신왕', 'main-echoes/the-false-sovereign.webp', '에코 어빌리티를 사용하여 거짓의 신왕으로 변신한 후 회전하면서 돌진하여 적에게 55.35%의 전도 피해를 4단 입힌다. 변주 스킬을 사용하여 등장 시 거짓의 신왕을 소환하여 적에게 405.00%의 전도 피해를 입힌다. 초기 2회 사용 가능 횟수를 보유하며, 8초마다 사용 횟수가 1회씩 증가하고, 사용 가능 횟수의 누적 최대치는 2회이다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 전도 피해 보너스가 12.00% 증가되고, 강공격 피해 보너스가 12.00% 증가된다.', 38),
    ('lady-of-the-sea', '바다의 여인', 'main-echoes/lady-of-the-sea.webp', '에코 어빌리티를 사용하여 「파도의 소용돌이」를 소환한 후, 적에게 최대 10단 13.68% 및 1단 164.16%의 기류 피해 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 기류 피해 보너스가 12.00% 증가되고, 공명 해방 피해 보너스가 12.00% 증가된다.', 39),
    ('hyvatia', '하이와티아', 'main-echoes/hyvatia.webp', '에코 어빌리티를 사용하여 하이와티아를 소환한 후, 공중에서 레이저를 발사하여 적에게 10단 27.36%의 회절 피해를 입힌다. 이후 15초 내에 자신이 반주 스킬 발동 시, 다음번 변주 스킬로 등장하는 캐릭터의 전체 속성 피해 보너스를 10.00% 증가시키고, 15초간 지속된다.', NULL, 40),
    ('reactor-husk', '리액터 허스크', 'main-echoes/reactor-husk.webp', '에코 어빌리티를 사용하여 리액터 허스크로 변신한 후, 공중으로 뛰어올라 중참을 가하여 적에게 351.00%의 용융 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 공명 효율이 10.00% 증가된다.', 41),
    ('nameless-explorer', '이름없는 탐색자', 'main-echoes/nameless-explorer.webp', '에코 어빌리티를 사용하여 이름없는 탐색자를 소환한 후, 경로에 있는 적을 관통하여 273.60%의 기류 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 기류 피해 보너스가 12.00% 증가되고, 에코 어빌리티 피해 보너스가 20.00% 증가된다.', 42),
    ('z04-sigillum', '시길룸', 'main-echoes/z04-sigillum.webp', '에코 어빌리티를 사용하여 시길룸을 소환한 후, 적에게 1단 68.40%와 2단 205.20%의 용융 피해를 입힌다.', '에이메스가 메인 슬롯에 장착 시 공명 해방 피해 보너스가 25.00% 증가한다.', 43),
    ('myriad-snare-rustfire-chassis', '만와뢰 · 잔해', 'main-echoes/myriad-snare-rustfire-chassis.webp', '에코 어빌리티를 사용하여 만와뢰 · 잔해를 소환한 후, 우선 적에게 HP 최대치의 10.20%에 해당하는 용융 피해를 입히고, 해당 기간 동안 경로상의 적을 최대 19회까지 연속으로 짓밟으며, 1회마다 HP 최대치의 0.37%에 해당하는 용융 피해를 입힌다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 용융 피해 보너스가 12.00% 증가되고, 강공격 피해 보너스가 12.00% 증가된다.', 44),
    ('thousand-puppet-pavilion', '천괴중루', 'main-echoes/thousand-puppet-pavilion.webp', '에코 어빌리티를 사용하여 주변 적에게 109.44%의 인멸 피해를 입히고, 4자루의 「수많은 기억 속 검의 소리」를 소환하며 15초간 지속된다. 「수많은 기억 속 검의 소리」가 존재하는 기간 동안, 자신이 목표에게 「암흑 효과」 추가 시, 「수많은 기억 속 검의 소리」 1자루를 소모하여 목표에게 41.04%의 인멸 피해를 1회 입히며, 1초마다 1회 발생할 수 있다.', '메인 슬롯에 해당 에코 어빌리티를 장착 시, 자신의 인멸 피해 보너스가 12.00% 증가되고, 강공격 피해 보너스가 12.00% 증가된다.', 45);

INSERT INTO main_echo_bonuses (main_echo_id, sort_order, category, value) VALUES
    ('capitaneus', 1, '회절 피해 보너스', 12),
    ('capitaneus', 2, '강공격 피해', 12),
    ('corrosaurus', 1, '용융 피해 보너스', 12),
    ('corrosaurus', 2, '에코 피해', 20),
    ('forbidden-bastion', 1, '치료 효과', 10),
    ('lorelei', 1, '인멸 피해 보너스', 12),
    ('lorelei', 2, '일반 공격 피해', 12),
    ('sentry-construct', 1, '응결 피해 보너스', 12),
    ('sentry-construct', 2, '공명 스킬 피해', 12),
    ('dragon-of-dirge', 1, '용융 피해 보너스', 12),
    ('dragon-of-dirge', 2, '일반 공격 피해', 12),
    ('nightmare-feilian-beringal', 1, '기류 피해 보너스', 12),
    ('nightmare-feilian-beringal', 2, '강공격 피해', 12),
    ('nightmare-impermanence-heron', 1, '인멸 피해 보너스', 12),
    ('nightmare-impermanence-heron', 2, '강공격 피해', 12),
    ('nightmare-thundering-mephis', 1, '전도 피해 보너스', 12),
    ('nightmare-thundering-mephis', 2, '공명 해방 피해', 12),
    ('nightmare-tempest-mephis', 1, '전도 피해 보너스', 12),
    ('nightmare-tempest-mephis', 2, '공명 스킬 피해', 12),
    ('nightmare-crownless', 1, '인멸 피해 보너스', 12),
    ('nightmare-crownless', 2, '일반 공격 피해', 12),
    ('nightmare-inferno-rider', 1, '용융 피해 보너스', 12),
    ('nightmare-inferno-rider', 2, '공명 스킬 피해', 12),
    ('nightmare-mourning-aix', 1, '회절 피해 보너스', 12),
    ('nightmare-lampylumen-myriad', 1, '응결 피해 보너스', 12),
    ('nightmare-kelpie', 1, '응결 피해 보너스', 12),
    ('nightmare-kelpie', 2, '기류 피해 보너스', 12),
    ('nightmare-hecate', 1, '인멸 피해 보너스', 12),
    ('nightmare-hecate', 2, '에코 피해', 20),
    ('reminiscence-fleurdelys', 1, '기류 피해 보너스', 10),
    ('reminiscence-fenrico', 1, '기류 피해 보너스', 12),
    ('reminiscence-fenrico', 2, '강공격 피해', 12),
    ('reminiscence-threnodian-leviathan', 1, '인멸 피해 보너스', 12),
    ('reminiscence-threnodian-leviathan', 2, '공명 해방 피해', 12),
    ('reminiscence-threnodian-voidborne-construct', 1, '응결 피해 보너스', 12),
    ('reminiscence-threnodian-voidborne-construct', 2, '공명 해방 피해', 12),
    ('lioness-of-glory', 1, '용융 피해 보너스', 12),
    ('lioness-of-glory', 2, '공명 해방 피해', 12),
    ('the-false-sovereign', 1, '전도 피해 보너스', 12),
    ('the-false-sovereign', 2, '강공격 피해', 12),
    ('lady-of-the-sea', 1, '기류 피해 보너스', 12),
    ('lady-of-the-sea', 2, '공명 해방 피해', 12),
    ('reactor-husk', 1, '공명 효율', 10),
    ('nameless-explorer', 1, '기류 피해 보너스', 12),
    ('nameless-explorer', 2, '에코 피해', 20),
    ('myriad-snare-rustfire-chassis', 1, '용융 피해 보너스', 12),
    ('myriad-snare-rustfire-chassis', 2, '강공격 피해', 12),
    ('thousand-puppet-pavilion', 1, '인멸 피해 보너스', 12),
    ('thousand-puppet-pavilion', 2, '강공격 피해', 12);

INSERT INTO main_echo_character_bonuses (main_echo_id, character_id, sort_order, category, value) VALUES
    ('reminiscence-fleurdelys', 'rover_aero', 1, '기류 피해 보너스', 10),
    ('reminiscence-fleurdelys', 'cartethyia', 1, '기류 피해 보너스', 10),
    ('reminiscence-nightmare-adam-smasher', 'lucy', 1, '크리티컬', 15),
    ('reminiscence-nightmare-adam-smasher', 'rebecca', 1, '크리티컬', 15),
    ('z04-sigillum', 'aemeath', 1, '공명 해방 피해', 25);

INSERT INTO main_echo_character_descriptions (main_echo_id, character_id, description) VALUES
    ('reminiscence-nightmare-adam-smasher', 'lucy', '에코 어빌리티를 짧게 누르면 주변 목표에게 273.60%의 회절 피해를 입힌다. 길게 누르면 주변 목표에게 273.60%의 회절 피해를 입히고, 특수 이동 상태에 진입하며 지속 기간 동안 루시의 이동 속도를 증가시키고 주변 목표의 시간 흐름을 늦춘다.'),
    ('reminiscence-nightmare-adam-smasher', 'rebecca', '에코 어빌리티 사용 시, 미사일을 발사하여 목표에게 16단 17.10%의 전도 피해를 입힌다.');

INSERT INTO echo_set_main_echoes (set_id, main_echo_id, sort_order) VALUES
    ('heart-of-evils-purge', 'myriad-snare-rustfire-chassis', 1),
    ('heart-of-evils-purge', 'forbidden-bastion', 2),
    ('lamp-of-nether-road', 'myriad-snare-rustfire-chassis', 1),
    ('lamp-of-nether-road', 'forbidden-bastion', 2),
    ('song-of-feathered-trace', 'thousand-puppet-pavilion', 1),
    ('song-of-feathered-trace', 'forbidden-bastion', 2),
    ('shadow-of-shattered-dreams', 'reminiscence-nightmare-adam-smasher', 1),
    ('reel-of-spliced-memories', 'nameless-explorer', 1),
    ('wishes-of-quiet-snowfall', 'reminiscence-threnodian-voidborne-construct', 1),
    ('sound-of-true-name', 'nameless-explorer', 1),
    ('chromatic-foam', 'reactor-husk', 1),
    ('chromatic-foam', 'reminiscence-denia', 2),
    ('trailblazing-star', 'z04-sigillum', 1),
    ('rite-of-gilded-revelation', 'hyvatia', 1),
    ('halo-of-starry-radiance', 'reactor-husk', 1),
    ('pact-of-neonlight-leap', 'hyvatia', 1),
    ('thread-of-severed-fate', 'reminiscence-threnodian-leviathan', 1),
    ('flamewings-shadow', 'reminiscence-threnodian-leviathan', 1),
    ('flamewings-shadow', 'corrosaurus', 2),
    ('law-of-harmony', 'reminiscence-fenrico', 1),
    ('crown-of-valor', 'the-false-sovereign', 1),
    ('crown-of-valor', 'lady-of-the-sea', 2),
    ('dream-of-the-lost', 'nightmare-hecate', 1),
    ('dream-of-the-lost', 'reminiscence-fenrico', 2),
    ('flaming-clawprint', 'lioness-of-glory', 1),
    ('flaming-clawprint', 'corrosaurus', 2),
    ('windward-pilgrimage', 'reminiscence-fleurdelys', 1),
    ('windward-pilgrimage', 'nightmare-kelpie', 2),
    ('gusts-of-welkin', 'reminiscence-fleurdelys', 1),
    ('gusts-of-welkin', 'nightmare-kelpie', 2),
    ('tidebreaking-courage', 'dragon-of-dirge', 1),
    ('empyrean-anthem', 'hecate', 1),
    ('empyrean-anthem', 'nightmare-tempest-mephis', 2),
    ('empyrean-anthem', 'nightmare-lampylumen-myriad', 3),
    ('eternal-radiance', 'nightmare-mourning-aix', 1),
    ('eternal-radiance', 'capitaneus', 2),
    ('frosty-resolve', 'sentry-construct', 1),
    ('frosty-resolve', 'nightmare-lampylumen-myriad', 2),
    ('lingering-tunes', 'mech-abomination', 1),
    ('moonlit-clouds', 'bell-borne-geochelone', 1),
    ('moonlit-clouds', 'impermanence-heron', 2),
    ('rejuvenating-glow', 'bell-borne-geochelone', 1),
    ('rejuvenating-glow', 'fallacy-of-no-return', 2),
    ('havoc-eclipse', 'crownless', 1),
    ('havoc-eclipse', 'dreamless', 2),
    ('havoc-eclipse', 'nightmare-crownless', 3),
    ('celestial-light', 'mourning-aix', 1),
    ('celestial-light', 'jue', 2),
    ('sierra-gale', 'feilian-beringal', 1),
    ('sierra-gale', 'nightmare-feilian-beringal', 2),
    ('void-thunder', 'thundering-mephis', 1),
    ('void-thunder', 'nightmare-thundering-mephis', 2),
    ('void-thunder', 'tempest-mephis', 3),
    ('void-thunder', 'nightmare-tempest-mephis', 4),
    ('molten-rift', 'inferno-rider', 1),
    ('molten-rift', 'nightmare-inferno-rider', 2),
    ('freezing-frost', 'lampylumen-myriad', 1);

INSERT INTO character_recommended_weapons (character_id, weapon_id, sort_order) VALUES
    ('jiyan', 'verdant-summit', 1),
    ('jiyan', 'lustrous-razor', 2),
    ('jiyan', 'autumntrace', 3),
    ('ciaccona', 'woodland-aria', 1),
    ('ciaccona', 'static-mist', 2),
    ('ciaccona', 'cadenza', 3),
    ('cartethyia', 'defiers-thorn', 1),
    ('cartethyia', 'red-spring', 2),
    ('rover_aero', 'bloodpacts-pledge', 1),
    ('rover_aero', 'emerald-of-genesis', 2),
    ('rover_aero', 'overture', 3),
    ('iuno', 'moongazers-sigil', 1),
    ('iuno', 'veritys-handle', 2),
    ('iuno', 'blazing-justice', 3),
    ('iuno', 'abyss-surges', 4),
    ('qiuyuan', 'emerald-sentence', 1),
    ('qiuyuan', 'red-spring', 2),
    ('qiuyuan', 'blazing-brilliance', 3),
    ('qiuyuan', 'emerald-of-genesis', 4),
    ('sigrika', 'solsworn-ciphers', 1),
    ('sigrika', 'blazing-justice', 2),
    ('sigrika', 'daybreakers-spine', 3),
    ('encore', 'stringmaster', 1),
    ('encore', 'rime-draped-sprouts', 2),
    ('encore', 'cosmic-ripples', 3),
    ('encore', 'augment', 4),
    ('changli', 'blazing-brilliance', 1),
    ('changli', 'emerald-of-genesis', 2),
    ('changli', 'commando-of-conviction', 3),
    ('brant', 'unflickering-valor', 1),
    ('brant', 'red-spring', 2),
    ('brant', 'emerald-of-genesis', 3),
    ('brant', 'overture', 4),
    ('lupa', 'wildfire-mark', 1),
    ('lupa', 'ages-of-harvest', 2),
    ('lupa', 'verdant-summit', 3),
    ('lupa', 'lustrous-razor', 4),
    ('galbrena', 'lux-umbra', 1),
    ('galbrena', 'the-last-dance', 2),
    ('galbrena', 'static-mist', 3),
    ('galbrena', 'woodland-aria', 4),
    ('mornye', 'starfield-calibrator', 1),
    ('mornye', 'discord', 2),
    ('aemeath', 'eternal-radiance', 1),
    ('aemeath', 'emerald-of-genesis', 2),
    ('aemeath', 'red-spring', 3),
    ('aemeath', 'emerald-sentence', 4),
    ('denia', 'forged-dwarf-star', 1),
    ('denia', 'stringmaster', 2),
    ('denia', 'lethean-elegy', 3),
    ('zhezhi', 'rime-draped-sprouts', 1),
    ('zhezhi', 'stringmaster', 2),
    ('zhezhi', 'cosmic-ripples', 3),
    ('zhezhi', 'augment', 4),
    ('carlotta', 'the-last-dance', 1),
    ('carlotta', 'static-mist', 2),
    ('carlotta', 'thunderbolt', 3),
    ('lingyang', 'blazing-justice', 1),
    ('lingyang', 'veritys-handle', 2),
    ('lingyang', 'abyss-surges', 3),
    ('lingyang', 'celestial-spiral', 4),
    ('hiyuki', 'frostburn', 1),
    ('hiyuki', 'emerald-of-genesis', 2),
    ('hiyuki', 'blazing-brilliance', 3),
    ('lucilla', 'freeze-frame', 1),
    ('lucilla', 'stringmaster', 2),
    ('lucilla', 'rime-draped-sprouts', 3),
    ('suisui', 'variation', 1),
    ('suisui', 'firstlights-herald', 2),
    ('yinlin', 'stringmaster', 1),
    ('yinlin', 'rime-draped-sprouts', 2),
    ('yinlin', 'cosmic-ripples', 3),
    ('yinlin', 'augment', 4),
    ('calcharo', 'ages-of-harvest', 1),
    ('calcharo', 'verdant-summit', 2),
    ('calcharo', 'lustrous-razor', 3),
    ('calcharo', 'autumntrace', 4),
    ('xiangli_yao', 'veritys-handle', 1),
    ('xiangli_yao', 'abyss-surges', 2),
    ('xiangli_yao', 'stonard', 3),
    ('augusta', 'thunderflare-dominion', 1),
    ('augusta', 'verdant-summit', 2),
    ('augusta', 'ages-of-harvest', 3),
    ('augusta', 'lustrous-razor', 4),
    ('rebecca', 'skull-thrasher', 1),
    ('rebecca', 'static-mist', 2),
    ('rebecca', 'phasic-homogenizer', 3),
    ('rover_havoc', 'emerald-of-genesis', 1),
    ('rover_havoc', 'blazing-brilliance', 2),
    ('rover_havoc', 'commando-of-conviction', 3),
    ('camellya', 'red-spring', 1),
    ('camellya', 'emerald-of-genesis', 2),
    ('camellya', 'commando-of-conviction', 3),
    ('roccia', 'tragicomedy', 1),
    ('roccia', 'veritys-handle', 2),
    ('roccia', 'abyss-surges', 3),
    ('roccia', 'stonard', 4),
    ('cantarella', 'whispers-of-sirens', 1),
    ('cantarella', 'stringmaster', 2),
    ('cantarella', 'cosmic-ripples', 3),
    ('cantarella', 'augment', 4),
    ('phrolova', 'lethean-elegy', 1),
    ('phrolova', 'stringmaster', 2),
    ('phrolova', 'cosmic-ripples', 3),
    ('phrolova', 'augment', 4),
    ('chisa', 'kumokiri', 1),
    ('chisa', 'wildfire-mark', 2),
    ('chisa', 'lustrous-razor', 3),
    ('rover_spectro', 'emerald-of-genesis', 1),
    ('rover_spectro', 'blazing-brilliance', 2),
    ('rover_spectro', 'commando-of-conviction', 3),
    ('verina', 'variation', 1),
    ('verina', 'call-of-the-abyss', 2),
    ('verina', 'stellar-symphony', 3),
    ('jinhsi', 'ages-of-harvest', 1),
    ('jinhsi', 'lustrous-razor', 2),
    ('jinhsi', 'autumntrace', 3),
    ('shorekeeper', 'stellar-symphony', 1),
    ('shorekeeper', 'variation', 2),
    ('shorekeeper', 'rectifier-of-voyager', 3),
    ('phoebe', 'luminous-hymn', 1),
    ('phoebe', 'stringmaster', 2),
    ('phoebe', 'rime-draped-sprouts', 3),
    ('phoebe', 'oceans-gift', 4),
    ('zeni', 'blazing-justice', 1),
    ('zeni', 'tragicomedy', 2),
    ('zeni', 'celestial-spiral', 3),
    ('zeni', 'stonard', 4),
    ('lynae', 'spectrum-blaster', 1),
    ('lynae', 'static-mist', 2),
    ('lynae', 'phasic-homogenizer', 3),
    ('luuk_herssen', 'daybreakers-spine', 1),
    ('luuk_herssen', 'pulsation-bracer', 2),
    ('luuk_herssen', 'blazing-justice', 3),
    ('lucy', 'spectral-trigger', 1),
    ('lucy', 'phasic-homogenizer', 2),
    ('lucy', 'skull-thrasher', 3);

INSERT INTO character_echo_combos (character_id, combo_no) VALUES
    ('jiyan', 1),
    ('ciaccona', 1),
    ('cartethyia', 1),
    ('rover_aero', 1),
    ('rover_aero', 2),
    ('iuno', 1),
    ('iuno', 2),
    ('iuno', 3),
    ('iuno', 4),
    ('qiuyuan', 1),
    ('qiuyuan', 2),
    ('qiuyuan', 3),
    ('qiuyuan', 4),
    ('sigrika', 1),
    ('encore', 1),
    ('changli', 1),
    ('brant', 1),
    ('lupa', 1),
    ('galbrena', 1),
    ('galbrena', 2),
    ('mornye', 1),
    ('aemeath', 1),
    ('denia', 1),
    ('denia', 2),
    ('zhezhi', 1),
    ('zhezhi', 2),
    ('carlotta', 1),
    ('lingyang', 1),
    ('hiyuki', 1),
    ('lucilla', 1),
    ('lucilla', 2),
    ('suisui', 1),
    ('yinlin', 1),
    ('yinlin', 2),
    ('calcharo', 1),
    ('xiangli_yao', 1),
    ('augusta', 1),
    ('rebecca', 1),
    ('rover_havoc', 1),
    ('camellya', 1),
    ('roccia', 1),
    ('cantarella', 1),
    ('cantarella', 2),
    ('phrolova', 1),
    ('phrolova', 2),
    ('chisa', 1),
    ('chisa', 2),
    ('chisa', 3),
    ('rover_spectro', 1),
    ('verina', 1),
    ('jinhsi', 1),
    ('shorekeeper', 1),
    ('phoebe', 1),
    ('zeni', 1),
    ('lynae', 1),
    ('luuk_herssen', 1),
    ('lucy', 1);

INSERT INTO character_echo_combo_parts (character_id, combo_no, sort_order, set_id, piece_count) VALUES
    ('jiyan', 1, 1, 'sierra-gale', 5),
    ('ciaccona', 1, 1, 'gusts-of-welkin', 5),
    ('cartethyia', 1, 1, 'windward-pilgrimage', 5),
    ('rover_aero', 1, 1, 'windward-pilgrimage', 5),
    ('rover_aero', 2, 1, 'rejuvenating-glow', 5),
    ('iuno', 1, 1, 'crown-of-valor', 3),
    ('iuno', 1, 2, 'sierra-gale', 2),
    ('iuno', 2, 1, 'crown-of-valor', 3),
    ('iuno', 2, 2, 'gusts-of-welkin', 2),
    ('iuno', 3, 1, 'crown-of-valor', 3),
    ('iuno', 3, 2, 'windward-pilgrimage', 2),
    ('iuno', 4, 1, 'moonlit-clouds', 5),
    ('qiuyuan', 1, 1, 'law-of-harmony', 3),
    ('qiuyuan', 1, 2, 'sierra-gale', 2),
    ('qiuyuan', 2, 1, 'law-of-harmony', 3),
    ('qiuyuan', 2, 2, 'gusts-of-welkin', 2),
    ('qiuyuan', 3, 1, 'law-of-harmony', 3),
    ('qiuyuan', 3, 2, 'windward-pilgrimage', 2),
    ('qiuyuan', 4, 1, 'moonlit-clouds', 5),
    ('sigrika', 1, 1, 'sound-of-true-name', 5),
    ('encore', 1, 1, 'molten-rift', 5),
    ('changli', 1, 1, 'molten-rift', 5),
    ('brant', 1, 1, 'tidebreaking-courage', 5),
    ('lupa', 1, 1, 'flaming-clawprint', 5),
    ('galbrena', 1, 1, 'flamewings-shadow', 3),
    ('galbrena', 1, 2, 'molten-rift', 2),
    ('galbrena', 2, 1, 'flamewings-shadow', 3),
    ('galbrena', 2, 2, 'flaming-clawprint', 2),
    ('mornye', 1, 1, 'halo-of-starry-radiance', 5),
    ('aemeath', 1, 1, 'trailblazing-star', 5),
    ('denia', 1, 1, 'chromatic-foam', 5),
    ('denia', 2, 1, 'reel-of-spliced-memories', 5),
    ('zhezhi', 1, 1, 'moonlit-clouds', 5),
    ('zhezhi', 2, 1, 'empyrean-anthem', 5),
    ('carlotta', 1, 1, 'frosty-resolve', 5),
    ('lingyang', 1, 1, 'freezing-frost', 5),
    ('hiyuki', 1, 1, 'wishes-of-quiet-snowfall', 5),
    ('lucilla', 1, 1, 'wishes-of-quiet-snowfall', 5),
    ('lucilla', 2, 1, 'moonlit-clouds', 5),
    ('suisui', 1, 1, 'song-of-feathered-trace', 5),
    ('yinlin', 1, 1, 'moonlit-clouds', 5),
    ('yinlin', 2, 1, 'empyrean-anthem', 5),
    ('calcharo', 1, 1, 'void-thunder', 5),
    ('xiangli_yao', 1, 1, 'void-thunder', 5),
    ('augusta', 1, 1, 'crown-of-valor', 3),
    ('augusta', 1, 2, 'void-thunder', 2),
    ('rebecca', 1, 1, 'shadow-of-shattered-dreams', 1),
    ('rebecca', 1, 2, 'lingering-tunes', 2),
    ('rebecca', 1, 3, 'reel-of-spliced-memories', 2),
    ('rover_havoc', 1, 1, 'havoc-eclipse', 5),
    ('camellya', 1, 1, 'havoc-eclipse', 5),
    ('roccia', 1, 1, 'abyssal-veil', 5),
    ('cantarella', 1, 1, 'abyssal-veil', 5),
    ('cantarella', 2, 1, 'moonlit-clouds', 5),
    ('phrolova', 1, 1, 'dream-of-the-lost', 3),
    ('phrolova', 1, 2, 'havoc-eclipse', 2),
    ('phrolova', 2, 1, 'dream-of-the-lost', 3),
    ('phrolova', 2, 2, 'abyssal-veil', 2),
    ('chisa', 1, 1, 'thread-of-severed-fate', 3),
    ('chisa', 1, 2, 'havoc-eclipse', 2),
    ('chisa', 2, 1, 'thread-of-severed-fate', 3),
    ('chisa', 2, 2, 'abyssal-veil', 2),
    ('chisa', 3, 1, 'thread-of-severed-fate', 3),
    ('chisa', 3, 2, 'moonlit-clouds', 2),
    ('rover_spectro', 1, 1, 'celestial-light', 5),
    ('verina', 1, 1, 'rejuvenating-glow', 5),
    ('jinhsi', 1, 1, 'celestial-light', 5),
    ('shorekeeper', 1, 1, 'rejuvenating-glow', 5),
    ('phoebe', 1, 1, 'eternal-radiance', 5),
    ('zeni', 1, 1, 'eternal-radiance', 5),
    ('lynae', 1, 1, 'pact-of-neonlight-leap', 5),
    ('luuk_herssen', 1, 1, 'rite-of-gilded-revelation', 5),
    ('lucy', 1, 1, 'shadow-of-shattered-dreams', 1),
    ('lucy', 1, 2, 'lingering-tunes', 2),
    ('lucy', 1, 3, 'reel-of-spliced-memories', 2);

INSERT INTO character_valid_options (character_id, label, sort_order) VALUES
    ('aemeath', '크리티컬%', 1),
    ('aemeath', '크리티컬 피해%', 2),
    ('aemeath', '공격력%', 3),
    ('aemeath', '공명 효율%', 4),
    ('aemeath', '공격력', 5),
    ('aemeath', '공명 해방 피해 보너스%', 6),
    ('lingyang', '크리티컬%', 1),
    ('lingyang', '크리티컬 피해%', 2),
    ('lingyang', '공격력%', 3),
    ('lingyang', '공명 효율%', 4),
    ('lingyang', '공격력', 5),
    ('zhezhi', '크리티컬%', 1),
    ('zhezhi', '크리티컬 피해%', 2),
    ('zhezhi', '공격력%', 3),
    ('zhezhi', '공명 효율%', 4),
    ('zhezhi', '공격력', 5),
    ('zhezhi', '일반 공격 피해 보너스%', 6),
    ('carlotta', '크리티컬%', 1),
    ('carlotta', '크리티컬 피해%', 2),
    ('carlotta', '공격력%', 3),
    ('carlotta', '공명 효율%', 4),
    ('carlotta', '공격력', 5),
    ('carlotta', '공명 스킬 피해 보너스%', 6),
    ('lucilla', '크리티컬%', 1),
    ('lucilla', '크리티컬 피해%', 2),
    ('lucilla', '공격력%', 3),
    ('lucilla', '공명 효율%', 4),
    ('lucilla', '공격력', 5),
    ('lucilla', '일반 공격 피해 보너스%', 6),
    ('hiyuki', '크리티컬%', 1),
    ('hiyuki', '크리티컬 피해%', 2),
    ('hiyuki', '공격력%', 3),
    ('hiyuki', '공명 효율%', 4),
    ('hiyuki', '공격력', 5),
    ('hiyuki', '공명 해방 피해 보너스%', 6),
    ('suisui', '크리티컬%', 1),
    ('suisui', '크리티컬 피해%', 2),
    ('suisui', 'HP%', 3),
    ('suisui', '공명 효율%', 4),
    ('encore', '크리티컬%', 1),
    ('encore', '크리티컬 피해%', 2),
    ('encore', '공격력%', 3),
    ('encore', '공명 효율%', 4),
    ('encore', '공격력', 5),
    ('changli', '크리티컬%', 1),
    ('changli', '크리티컬 피해%', 2),
    ('changli', '공격력%', 3),
    ('changli', '공명 효율%', 4),
    ('changli', '공격력', 5),
    ('changli', '공명 스킬 피해 보너스%', 6),
    ('brant', '크리티컬%', 1),
    ('brant', '크리티컬 피해%', 2),
    ('brant', '공격력%', 3),
    ('brant', '공명 효율%', 4),
    ('brant', '공격력', 5),
    ('brant', '일반 공격 피해 보너스%', 6),
    ('lupa', '크리티컬%', 1),
    ('lupa', '크리티컬 피해%', 2),
    ('lupa', '공격력%', 3),
    ('lupa', '공명 효율%', 4),
    ('lupa', '공격력', 5),
    ('lupa', '공명 해방 피해 보너스%', 6),
    ('galbrena', '크리티컬%', 1),
    ('galbrena', '크리티컬 피해%', 2),
    ('galbrena', '공격력%', 3),
    ('galbrena', '공명 효율%', 4),
    ('galbrena', '공격력', 5),
    ('galbrena', '강공격 피해 보너스%', 6),
    ('mornye', '크리티컬%', 1),
    ('mornye', '크리티컬 피해%', 2),
    ('mornye', '방어력%', 3),
    ('mornye', '공명 해방 피해 보너스%', 4),
    ('mornye', '공명 효율%', 5),
    ('denia', '크리티컬%', 1),
    ('denia', '크리티컬 피해%', 2),
    ('denia', '공격력%', 3),
    ('denia', '공명 효율%', 4),
    ('denia', '공격력', 5),
    ('denia', '공명 해방 피해 보너스%', 6),
    ('calcharo', '크리티컬%', 1),
    ('calcharo', '크리티컬 피해%', 2),
    ('calcharo', '공격력%', 3),
    ('calcharo', '공명 효율%', 4),
    ('calcharo', '공격력', 5),
    ('yinlin', '크리티컬%', 1),
    ('yinlin', '크리티컬 피해%', 2),
    ('yinlin', '공격력%', 3),
    ('yinlin', '공명 효율%', 4),
    ('yinlin', '공격력', 5),
    ('yinlin', '공명 스킬 피해 보너스%', 6),
    ('xiangli_yao', '크리티컬%', 1),
    ('xiangli_yao', '크리티컬 피해%', 2),
    ('xiangli_yao', '공격력%', 3),
    ('xiangli_yao', '공명 효율%', 4),
    ('xiangli_yao', '공격력', 5),
    ('xiangli_yao', '공명 해방 피해 보너스%', 6),
    ('augusta', '크리티컬%', 1),
    ('augusta', '크리티컬 피해%', 2),
    ('augusta', '공격력%', 3),
    ('augusta', '공명 효율%', 4),
    ('augusta', '공격력', 5),
    ('augusta', '강공격 피해 보너스%', 6),
    ('rebecca', '크리티컬%', 1),
    ('rebecca', '크리티컬 피해%', 2),
    ('rebecca', '공격력%', 3),
    ('rebecca', '공명 효율%', 4),
    ('rebecca', '공격력', 5),
    ('rebecca', '일반 공격 피해 보너스%', 6),
    ('rover_electro', '크리티컬%', 1),
    ('rover_electro', '크리티컬 피해%', 2),
    ('rover_electro', '공격력%', 3),
    ('rover_electro', '공명 효율%', 4),
    ('rover_electro', '공격력', 5),
    ('jiyan', '크리티컬%', 1),
    ('jiyan', '크리티컬 피해%', 2),
    ('jiyan', '공격력%', 3),
    ('jiyan', '공명 효율%', 4),
    ('jiyan', '공격력', 5),
    ('jiyan', '강공격 피해 보너스%', 6),
    ('ciaccona', '크리티컬%', 1),
    ('ciaccona', '크리티컬 피해%', 2),
    ('ciaccona', '공격력%', 3),
    ('ciaccona', '공명 효율%', 4),
    ('ciaccona', '공격력', 5),
    ('ciaccona', '공명 해방 피해 보너스%', 6),
    ('rover_aero', '크리티컬%', 1),
    ('rover_aero', '크리티컬 피해%', 2),
    ('rover_aero', '공격력%', 3),
    ('rover_aero', '공명 효율%', 4),
    ('rover_aero', '공격력', 5),
    ('rover_aero', '공명 스킬 피해 보너스%', 6),
    ('cartethyia', '크리티컬%', 1),
    ('cartethyia', '크리티컬 피해%', 2),
    ('cartethyia', 'HP%', 3),
    ('cartethyia', '일반 공격 피해 보너스%', 4),
    ('cartethyia', '공명 효율%', 5),
    ('iuno', '크리티컬%', 1),
    ('iuno', '크리티컬 피해%', 2),
    ('iuno', '공격력%', 3),
    ('iuno', '공명 효율%', 4),
    ('iuno', '공격력', 5),
    ('iuno', '공명 해방 피해 보너스%', 6),
    ('qiuyuan', '크리티컬%', 1),
    ('qiuyuan', '크리티컬 피해%', 2),
    ('qiuyuan', '공격력%', 3),
    ('qiuyuan', '공명 효율%', 4),
    ('qiuyuan', '공격력', 5),
    ('qiuyuan', '강공격 피해 보너스%', 6),
    ('sigrika', '크리티컬%', 1),
    ('sigrika', '크리티컬 피해%', 2),
    ('sigrika', '공격력%', 3),
    ('sigrika', '공명 효율%', 4),
    ('sigrika', '공격력', 5),
    ('verina', '크리티컬%', 1),
    ('verina', '크리티컬 피해%', 2),
    ('verina', '공격력%', 3),
    ('verina', '공명 효율%', 4),
    ('verina', '공격력', 5),
    ('rover_spectro', '크리티컬%', 1),
    ('rover_spectro', '크리티컬 피해%', 2),
    ('rover_spectro', '공격력%', 3),
    ('rover_spectro', '공명 효율%', 4),
    ('rover_spectro', '공격력', 5),
    ('rover_spectro', '공명 스킬 피해 보너스%', 6),
    ('jinhsi', '크리티컬%', 1),
    ('jinhsi', '크리티컬 피해%', 2),
    ('jinhsi', '공격력%', 3),
    ('jinhsi', '공명 효율%', 4),
    ('jinhsi', '공격력', 5),
    ('jinhsi', '공명 스킬 피해 보너스%', 6),
    ('shorekeeper', '크리티컬%', 1),
    ('shorekeeper', '크리티컬 피해%', 2),
    ('shorekeeper', 'HP%', 3),
    ('shorekeeper', '공명 효율%', 4),
    ('phoebe', '크리티컬%', 1),
    ('phoebe', '크리티컬 피해%', 2),
    ('phoebe', '공격력%', 3),
    ('phoebe', '공명 효율%', 4),
    ('phoebe', '공격력', 5),
    ('phoebe', '강공격 피해 보너스%', 6),
    ('zeni', '크리티컬%', 1),
    ('zeni', '크리티컬 피해%', 2),
    ('zeni', '공격력%', 3),
    ('zeni', '공명 효율%', 4),
    ('zeni', '공격력', 5),
    ('zeni', '강공격 피해 보너스%', 6),
    ('lynae', '크리티컬%', 1),
    ('lynae', '크리티컬 피해%', 2),
    ('lynae', '공격력%', 3),
    ('lynae', '공명 효율%', 4),
    ('lynae', '공격력', 5),
    ('lynae', '일반 공격 피해 보너스%', 6),
    ('luuk_herssen', '크리티컬%', 1),
    ('luuk_herssen', '크리티컬 피해%', 2),
    ('luuk_herssen', '공격력%', 3),
    ('luuk_herssen', '공명 효율%', 4),
    ('luuk_herssen', '공격력', 5),
    ('luuk_herssen', '일반 공격 피해 보너스%', 6),
    ('lucy', '크리티컬%', 1),
    ('lucy', '크리티컬 피해%', 2),
    ('lucy', '공격력%', 3),
    ('lucy', '공명 효율%', 4),
    ('lucy', '공격력', 5),
    ('lucy', '강공격 피해 보너스%', 6),
    ('camellya', '크리티컬%', 1),
    ('camellya', '크리티컬 피해%', 2),
    ('camellya', '공격력%', 3),
    ('camellya', '공명 효율%', 4),
    ('camellya', '공격력', 5),
    ('camellya', '일반 공격 피해 보너스%', 6),
    ('rover_havoc', '크리티컬%', 1),
    ('rover_havoc', '크리티컬 피해%', 2),
    ('rover_havoc', '공격력%', 3),
    ('rover_havoc', '공명 효율%', 4),
    ('rover_havoc', '공격력', 5),
    ('rover_havoc', '공명 스킬 피해 보너스%', 6),
    ('roccia', '크리티컬%', 1),
    ('roccia', '크리티컬 피해%', 2),
    ('roccia', '공격력%', 3),
    ('roccia', '공명 효율%', 4),
    ('roccia', '공격력', 5),
    ('roccia', '강공격 피해 보너스%', 6),
    ('cantarella', '크리티컬%', 1),
    ('cantarella', '크리티컬 피해%', 2),
    ('cantarella', '공격력%', 3),
    ('cantarella', '공명 효율%', 4),
    ('cantarella', '공격력', 5),
    ('cantarella', '일반 공격 피해 보너스%', 6),
    ('phrolova', '크리티컬%', 1),
    ('phrolova', '크리티컬 피해%', 2),
    ('phrolova', '공격력%', 3),
    ('phrolova', '공명 효율%', 4),
    ('phrolova', '공격력', 5),
    ('phrolova', '공명 스킬 피해 보너스%', 6),
    ('chisa', '크리티컬%', 1),
    ('chisa', '크리티컬 피해%', 2),
    ('chisa', '공격력%', 3),
    ('chisa', '공명 효율%', 4),
    ('chisa', '공격력', 5),
    ('chisa', '공명 해방 피해 보너스%', 6),
    ('Yangyang_Xuanling', '크리티컬%', 1),
    ('Yangyang_Xuanling', '크리티컬 피해%', 2),
    ('Yangyang_Xuanling', '공격력%', 3),
    ('Yangyang_Xuanling', '공명 효율%', 4),
    ('Yangyang_Xuanling', '공격력', 5),
    ('Yangyang_Xuanling', '강공격 피해 보너스%', 6);
