/**
 * 캐릭터 선택 화면에 쓰는 데이터입니다.
 */
export const ELEMENTS = ['응결', '용융', '전도', '기류', '회절', '인멸']

export const CHARACTERS = [
  { id: "능양", name: "능양", rarity: 5, element: "회절", image: null, initials: "능양", color: "#fb923c" },
  { id: "절지", name: "절지", rarity: 5, element: "회절", image: null, initials: "절지", color: "#34d399" },
  { id: "카를로타", name: "카를로타", rarity: 5, element: "회절", image: null, initials: "카를", color: "#f87171" },
  { id: "루실라", name: "루실라", rarity: 5, element: "회절", image: null, initials: "루실", color: "#38bdf8" },
  { id: "히유키", name: "히유키", rarity: 5, element: "회절", image: null, initials: "히유", color: "#fbbf24" },
  { id: "수수", name: "수수", rarity: 5, element: "회절", image: null, initials: "수수", color: "#c084fc" },
  { id: "앙코", name: "앙코", rarity: 5, element: "회절", image: null, initials: "앙코", color: "#4ade80" },
  { id: "장리", name: "장리", rarity: 5, element: "회절", image: null, initials: "장리", color: "#f472b6" },
  { id: "브렌트", name: "브렌트", rarity: 5, element: "회절", image: null, initials: "브렌", color: "#6ee7f9" },
  { id: "루파", name: "루파", rarity: 5, element: "회절", image: null, initials: "루파", color: "#a78bfa" },
  { id: "갈브레나", name: "갈브레나", rarity: 5, element: "회절", image: null, initials: "갈브", color: "#fb923c" },
  { id: "모니에", name: "모니에", rarity: 5, element: "회절", image: null, initials: "모니", color: "#34d399" },
  { id: "aemeath", name: "에이메스", rarity: 5, element: "용융", weaponType: "직검", image: "/characters/aemeath.png", initials: "에이", color: "#f87171" },
  { id: "denia", name: "데니아", rarity: 5, element: "회절", image: "/characters/deni.png", initials: "데니", color: "#38bdf8" },
  { id: "카카루", name: "카카루", rarity: 5, element: "회절", image: null, initials: "카카", color: "#fbbf24" },
  { id: "음림", name: "음림", rarity: 5, element: "회절", image: null, initials: "음림", color: "#c084fc" },
  { id: "상리요", name: "상리요", rarity: 5, element: "회절", image: null, initials: "상리", color: "#4ade80" },
  { id: "아우구스타", name: "아우구스타", rarity: 5, element: "회절", image: null, initials: "아우", color: "#f472b6" },
  { id: "레베카", name: "레베카", rarity: 5, element: "회절", image: null, initials: "레베", color: "#6ee7f9" },
  { id: "방랑자·전도", name: "방랑자·전도", rarity: 5, element: "회절", image: null, initials: "방랑", color: "#a78bfa" },
  { id: "기염", name: "기염", rarity: 5, element: "회절", image: null, initials: "기염", color: "#fb923c" },
  { id: "감심", name: "감심", rarity: 5, element: "회절", image: null, initials: "감심", color: "#34d399" },
  { id: "샤콘", name: "샤콘", rarity: 5, element: "회절", image: null, initials: "샤콘", color: "#f87171" },
  { id: "방랑자·기류", name: "방랑자·기류", rarity: 5, element: "회절", image: null, initials: "방랑", color: "#38bdf8" },
  { id: "카르티시아", name: "카르티시아", rarity: 5, element: "회절", image: null, initials: "카르", color: "#fbbf24" },
  { id: "유노", name: "유노", rarity: 5, element: "회절", image: null, initials: "유노", color: "#c084fc" },
  { id: "구원", name: "구원", rarity: 5, element: "회절", image: null, initials: "구원", color: "#4ade80" },
  { id: "시그리카", name: "시그리카", rarity: 5, element: "회절", image: null, initials: "시그", color: "#f472b6" },
  { id: "벨리나", name: "벨리나", rarity: 5, element: "회절", image: null, initials: "벨리", color: "#6ee7f9" },
  { id: "방랑자·회절", name: "방랑자·회절", rarity: 5, element: "회절", image: null, initials: "방랑", color: "#a78bfa" },
  { id: "금희", name: "금희", rarity: 5, element: "회절", image: null, initials: "금희", color: "#fb923c" },
  { id: "파수인", name: "파수인", rarity: 5, element: "회절", image: null, initials: "파수", color: "#34d399" },
  { id: "페비", name: "페비", rarity: 5, element: "회절", image: null, initials: "페비", color: "#f87171" },
  { id: "젠니", name: "젠니", rarity: 5, element: "회절", image: null, initials: "젠니", color: "#38bdf8" },
  { id: "린네", name: "린네", rarity: 5, element: "회절", image: null, initials: "린네", color: "#fbbf24" },
  { id: "루크·헤르센", name: "루크·헤르센", rarity: 5, element: "회절", image: null, initials: "루크", color: "#c084fc" },
  { id: "루시", name: "루시", rarity: 5, element: "회절", image: null, initials: "루시", color: "#4ade80" },
  { id: "카멜리아", name: "카멜리아", rarity: 5, element: "회절", image: null, initials: "카멜", color: "#f472b6" },
  { id: "방랑자·인멸", name: "방랑자·인멸", rarity: 5, element: "회절", image: null, initials: "방랑", color: "#6ee7f9" },
  { id: "로코코", name: "로코코", rarity: 5, element: "회절", image: null, initials: "로코", color: "#a78bfa" },
  { id: "칸타렐라", name: "칸타렐라", rarity: 5, element: "회절", image: null, initials: "칸타", color: "#fb923c" },
  { id: "플로로", name: "플로로", rarity: 5, element: "회절", image: null, initials: "플로", color: "#34d399" },
  { id: "치사", name: "치사", rarity: 5, element: "회절", image: null, initials: "치사", color: "#f87171" },
  { id: "Yangyang_Xuanling", name: "양양·현령", rarity: 5, element: "회절", image: "/characters/yangyang_xuanling.png", initials: "양양", color: "#38bdf8" },
]
